C={}
def ch(i,text,reason,cross): C[str(i)]={'text':text,'reason':reason,'cross':cross}
def style(i,text,reason='Mevcut Türkçe temel anlamı taşıyordu ancak sözdizimi, hitap düzeyi veya konuşma doğallığı zayıftı; satır tüm diller okunarak doğal Türkçeyle yeniden kuruldu.',cross='JP özgün metin ile FR/DE/IT/ES aynı temel anlamı doğruluyor; değişiklik bilgi eklemeden Türkçe akış, ton ve karakter sesi için yapıldı.'):
    ch(i,text,reason,cross)
def critical(i,text,reason='Mevcut Türkçede anlam, özne/nesne ilişkisi veya sahne mantığını etkileyen bir hata vardı; satır tüm dillerle karşılaştırılarak düzeltildi.',cross='JP özgün metin ve diğer resmî yerelleştirmelerin ortak anlamı yeni Türkçeyi destekliyor.'):
    ch(i,text,reason,cross)
def sound(i,text):
    ch(i,text,'Pokémon vokalizasyonu “çığlık” olarak genellenmişti; sahne etiketi bağlamı bozmadan nötr “Pokémon sesi” biçiminde standardize edildi.','JP 鳴き声 nötr bir Pokémon sesi/vokalizasyonu belirtir; EN de “Pokémon cry” teknik etikettir. Bu satırda gerçek bir çığlık anlamı zorunlu değil.')
def term(i,text,reason='Mevcut Türkçedeki terim bağlama veya önceki manuel terminolojiye uymuyordu; çok-dilli karşılaştırmayla tutarlılaştırıldı.',cross='JP ve FR/DE/IT/ES karşılıkları aynı kavramı doğruluyor; önceki manuel turlarda kullanılan Türkçe terminolojiyle tutarlılık sağlandı.'):
    ch(i,text,reason,cross)

# 0-49
style(0,'Mırıldanma','Yazım hatası düzeltildi: “Mirildanma” Türkçede “Mırıldanma” olmalı.','JP 鼻歌 ve EN “Humming” sözsüz mırıldanma/ezgi anlamını doğruluyor.')
critical(2,'Hey, Pikachu! Oo?\nSen dedektiflik bürosunun yeni elemanı mısın?','Mevcut Türkçe İngilizce yerelleştirmedeki “birlikte çalışıyor musunuz?” yorumunu izliyordu; özgün Japonca Tim’i dedektiflik bürosunun yeni çalışanı sanıyor.','JP 探偵事務所の新人くん = “dedektiflik bürosunun yeni elemanı”; DE/ES de yeni meslektaş/çalışan anlamına yakın. Bu nedenle özgün bilgi esas alındı.')
style(3,"Ee, hayır.\nBen Tim Goodman, Harry'nin oğluyum.\nTanıştığımıza memnun oldum.")
sound(5,'Pokémon sesi')
style(6,'Hadi ama, Ludicolo... Başında kahve fincanları varken{{CTRL:0001:0006:}}\nmüşteri böyle mi karşılanır!')
sound(7,'Pokémon sesi')
style(10,"Anladım... Harry'yi bilirsin.\nEminim bir gün hiç beklemediğimiz anda çıkıp gelir!")
critical(11,'Evet... umarım haklısındır.','Sahnenin duygusu kesinlikten çok temenni; mevcut “eminim haklısın” Tim’i gereğinden fazla kesin gösteriyordu.','JP そうですね daha yumuşak onay; DE “hoffentlich”, ES “eso espero” açıkça umut/temenni nüansı taşıyor.')
style(16,'Tabii ya.\nŞu zengin aromaya bak.\nAcılığın içindeki hoş asiditeyle\ndolgunluğun dengesi de mükemmel.\nBunu bir içtin mi\nbaşka kafeye gidemezsin.','Mevcut cümlede “içinecek” yazım/çekim hatası ve kahve tadım terminolojisinde mekanik yapı vardı; Pikachu’nun kahve meraklısı tonu korunarak yeniden kuruldu.','JP 芳醇な香り・酸味・苦味・コクのバランス ile FR/DE/IT aynı aroma, asidite, acılık ve gövde dengesini veriyor.')
style(25,'Son zamanlarda Pokémonlarla ilgili olaylar arttı.\nDikkatli ol.','“Daha fazla olay oluyor / dikkatli olun” hem yapay hem de Baker’ın tekil Tim’e hitabıyla uyumsuzdu.','JP 最近…事件が多い＋気をつけるんだよ ve FR/DE/IT/ES tekil Tim’e dikkat etmesini söylüyor.')
style(31,'Deneme, deneme...\nSanırım kapalı.')
style(33,'Yok canım! Mikrofonu görünce\nelimde olmadan—','“Olmaz!” reddetme bağlamında doğal değildi; Tim şarkı söyleme niyetini inkâr edip mikrofonu görünce refleksle denediğini söylüyor.','JP まさか＋マイクを見たらつい ve IT/ES “mikrofonu görünce kendiliğinden” nüansını doğruluyor.')
style(34,"Bu Pablo'nun koleksiyonu.\nCaz tarihinin büyük isimlerinin plakları var.")
style(35,'Klasik içeceklerin yanında\ndaha önce hiç görmediğim şeyler de var...','Mevcut Türkçe tek bir “standart içecek” ve tek bir bilinmeyen içecek varmış gibi daralıyordu.','JP 定番のドリンクと見たことのないドリンク ile FR/DE/IT/ES menüde klasik ve sıra dışı içecek çeşitleri olduğunu doğruluyor.')
style(38,'Annem de onu çocukça davranıyor diye\nhep azarlardı.','“Annem ona hep çocuk derdi” immaturity/çocukça davranma anlamını yanlış aktarıyordu.','JP 大人げないって…叱られてました = “çocukça davranıyor diye azarlanırdı”; FR/DE/IT/ES de davranışın çocuksuluğunu vurguluyor.')
style(39,'Haha, iyiymiş!')
style(45,'Sizce babam şimdi nerede olabilir?','Tim, kendinden yaşça büyük Pablo’ya kibar hitap ediyor; mevcut “sence” hitap düzeyini bozuyordu.','JP polite です/ます biçimi ve FR/DE/IT’de kibar hitap Tim’in Pablo’ya saygılı konuştuğunu destekliyor.')
style(46,'Şey... belki kahve kokan bir yerde?')
style(47,'Haklısınız galiba.\nBir yerlerde kahvesini içiyordur.','Tim’in Pablo’ya hitabı “siz” olarak tutarlılaştırıldı; cümle de doğal Türkçeye çekildi.','JP そうですね ve FR/DE/IT bağlamında Tim Pablo’ya saygılı konuşuyor; anlam Harry’nin bir yerlerde kahve içiyor olabileceği.')

# 50-99
style(51,'Ludicolo garson, değil mi?')
style(52,'Evet. Denemek için yardım etmesini istedim;\nişi de bayağı sevdi.','Mevcut Türkçe İngilizce yapıyı kelimesi kelimesine izleyip ağırlaşıyordu.','JP ためしに手伝ってもらったら仕事が気に入った ve FR/DE/IT/ES “denemelik yardım etti, işi sevdi” anlamında birleşiyor.')
style(53,'Kafeyi açalı çok oldu mu?')
style(54,'İki yılı yeni devirdik.\nBen eskiden piyano çalardım.')
style(55,'Müzisyen miydiniz?','Tim’in Pablo’ya hitap düzeyi dosya içinde kibar “siz” olarak tutarlılaştırıldı.','JP だったんですか ve FR/DE/IT’de kibar hitap biçimleri bunu destekliyor.')
style(58,'Bunu duymak güzel!\nBir kafenin özel harmanı, onun imzası gibidir.','“İşletmenin yüzü” Türkçede mekanik kalıyordu; kafenin özel harmanının kimliğini/ayırt edici yüzünü anlatan doğal karşılık seçildi.','JP 店の顔, FR image de marque, DE Aushängeschild, IT biglietto da visita aynı “işletmenin imzası/vitrini” metaforunu doğruluyor.')
style(60,'Vay, kafenin yıldızı da burada!\nBugün de keyfin yerinde.','Pikachu’nun Ludicolo’ya takılan/flörtöz tonu “herkesin görmeye geldiği kız” gibi yapay bir yapıya dönüşmüştü.','JP 看板娘, IT reginetta del locale ve DE “meine Hübsche” kafenin sevilen yüzü/flörtöz hitap tonunu destekliyor.')
critical(61,'Kız mı? Ludicolo dişi miydi yani?','“Dışı mı?” açık yazım/anlam hatasıydı; Tim Ludicolo’nun dişi olduğunu yeni fark ediyor.','JP メスだったのか, EN “It’s a she?”, DE/IT/ES dişi/cinsiyet bilgisini açıkça doğruluyor.')
style(68,'Bir fincan daha içmeyi çok isterdim ama\ngitmemiz gereken bir yer var.')
style(73,'Son zamanlarda artan Pokémon olayları hakkında\nbilgi toplamaya çalışıyorum.')
critical(74,'Bu okul ödevi falan mı?\nGNN haberlerini izlemelisin.\nSürekli özel haber yakalıyorlar.\nEkibi çok iyi olmalı.','“Hep bir şeyin izini sürer” scoop/özel haber anlamını kaybediyordu.','JP よくスクープをあげてる, IT “un sacco di scoop”, ES “mejores exclusivas”; GNN’nin özel haberleri sık yakaladığı ortak anlam.')
style(76,'Bu kafeye sık gelir misiniz?','Tim’in tanımadığı yetişkin kadına hitabı kibar “siz” olmalı; mevcut “gelir misin” fazla samimiydi.','JP ですか ve FR/DE/IT kibar hitap bunu destekliyor.')
style(77,"Evet. Pablo'nun piyano çaldığı zamanlardan beri\nhayranıyım.\nKahvesi de gerçekten çok iyi; özel harmanı harika.\nÜstelik ikinci katta bir dedektiflik bürosu varmış.\nBuraya ayrı bir gizem havası katıyor!",'Mevcut Türkçe parçalı ve “Ne gizemli!” gibi yapay bitiyordu; bilgi kaybetmeden doğal konuşma akışına getirildi.','JP/FR/DE/IT/ES Pablo’nun eski piyano hayranlığı, kahvenin kalitesi, özel harman ve üst kattaki dedektiflik bürosunun gizemli hava kattığını birlikte doğruluyor.')
style(79,'Hımm, bir çevrede tanınırdı.\nBilen bilirdi.','“İşin aslını bilenler” yanlış deyimdi; konuşmacı Pablo’nun geniş kitle değil belirli çevrelerde tanındığını söylüyor.','JP 知る人ぞ知る, DE Kennerkreisen, IT estimatori, ES determinados círculos aynı “bilenler arasında tanınır” nüansını veriyor.')
style(83,'O zaman hesabı öde.')
style(84,'(Emilia, kaçmalıyız!)','JP 逃げるわよ doğrudan “kaçmalıyız/kaçıyoruz”; “koşmamız lazım” eylemin amacını zayıflatıyordu.','JP ve sahne bağlamı tehlikeden kaçışı doğruluyor.')
sound(86,'Pokémon sesi (Iiii!)')
style(89,'Evet, hem de bir terslik var gibi.')
sound(91,'Pokémon sesi')
style(93,'Çabuk, gidelim!')
style(98,'Neyse, dikkatini üzerimize çekelim.','EN’deki “babble” teknik/performans notu Türkçede “mırıldanır” diye sahte bir eyleme dönüşmüştü; JP ve diğer diller repliğin doğrudan “neyse, dikkatini çekelim” olduğunu veriyor.','JP とにかくこっちに注意を引くぞ; FR/DE/IT/ES dikkat dağıtma/çekme anlamında birleşiyor.')

# 100-149
style(102,'Düzgün nişan alsana!','Mevcut “Gerçekten deniyor musun?!” İngilizce serbest uyarlamasını izliyor; özgün Japonca ve FR/DE doğrudan nişan alma doğruluğunu eleştiriyor.','JP ちゃんと狙えよ, FR “Vise mieux”, DE “Ziel etwas genauer” = düzgün/daha iyi nişan al.')
sound(103,'Pokémon sesi (fark eder)')
sound(104,'Pokémon sesi (Ne yapıyorsunuz siz?!)')
sound(105,'Pokémon sesi (Al bunu!)')
sound(118,'Pokémon sesi (Al bunu!)')
sound(120,'Pokémon sesi (Geliyorum! Hazır ol!)')
sound(127,'Pokémon sesi (Hıı-ya!)')
sound(129,'Pokémon sesi (Seni velet!)')
sound(130,'Pokémon sesi (Aaa!)')
sound(131,'Pokémon sesi (Uuugh...)')
style(134,'Aferin, Tim!','“Harika iş” İngilizce kalıbının mekanik aktarımıydı; kısa övgü doğal Türkçeye çekildi.','JP うまいぞ, FR/DE/IT/ES “iyi iş/aferin” anlamını doğruluyor.')
critical(138,'İşte son darbe!','Mevcut “Bu seni kendine getirir” saldırının anlamını tersine çevirip iyileştirme/ayıltma çağrışımı yapıyordu.','JP これでとどめだ, FR coup de grâce, ES golpe de gracia açıkça “son/bitirici darbe” diyor.')
style(140,'Hah!','JP えい fiziksel hamle sırasında çıkarılan efor ünlemi; “Evet!” anlamca yanlıştı.','JP sahne ünlemi ile EN “Yeah!” serbest uyarlaması karşılaştırıldı; eylem bağlamında kısa efor ünlemi seçildi.')
sound(141,'Pokémon sesi (Uuu...)')
style(142,'Görüşürüz, Glalie!\nAferin, Tim!\nŞimdi de hanımlara yardım edelim!','Son satır mevcut Türkçede eksik yüklemle kalmıştı; Pikachu’nun centilmen/oynak tonu doğal Türkçeyle tamamlandı.','JP お嬢さんたちを, FR/DE/IT/ES “hanımlara/kızlara yardım edelim” anlamını açıkça doğruluyor.')
critical(143,'Evet!','Mevcut “Hımmm...” yanlış duygu veriyordu; özgün Japonca açık onay ünlemidir.','JP うん！, FR Oui, DE Ja, ES Sí = “Evet!”')
style(144,'İyi misiniz?','Tim iki kadına birlikte sesleniyor; çoğul/kibar hitap Türkçede daha doğal.','ES açıkça çoğul “¿Estáis bien?”; sahnede Meiko ve Emilia ikisi de karşısında.')
style(145,'Hı? Bu yüz tanıdık...','Pikachu’nun Emilia’yı tanımaya başladığı an “o yüz ifadesi” şeklinde yanlış daralmıştı.','JP この顔, IT “una faccia nota”, ES “esta chica” tanıma/hatırlama anını doğruluyor.')
style(146,'Ben iyiyim ama... şu arkadaşım\nbacağını incitmiş de—')
style(148,'Hey, kendini zorlama!\nBize yardım ettiğin için teşekkürler.','Meiko ilk cümlede Emilia’ya tekil hitap ediyor; “zorlamayın” kişi uyumsuzdu.','JP 無理しないの ve FR/DE/IT/ES Emilia’ya tekil “kendini zorlama” uyarısı veriyor; ardından Tim’e teşekkür ediyor.')

# 150-199
style(151,'Aa! Sen yoksa o günkü—?','Mevcut “seni şuradan tanımıyor muyum” yapaydı; Emilia Tim’i daha önceki istasyon karşılaşmasından tanımaya başlıyor ve cümlesi yarıda kesiliyor.','JP もしかしてキミはあの時の, DE “Ich kenne dich! Du warst doch...”, ES “¿No nos vimos en...?” aynı tanıma anını veriyor.')
critical(158,'Emilia... Ne güzel isim.\nYine görüşmek ne güzel, tatlım—','Mevcut replik “biliyor—” diye anlamsız biçimde yarım kalıyordu; özgün Japonca Pikachu’nun flörtöz “tatlı kız...” hitabına başlarken kesiliyor.','JP かわいこちゃ… “tatlı/güzel kız...” diye yarım kalır; FR “très ch...”, DE/IT de flörtöz “hübsch/cara...” başlangıcını destekliyor.')
style(160,'Vay, ne enerjik kızmışsın.\nHı?')
style(161,'Bu bir televizyon kamerası.\nHiç görmedin mi? Mağaraya haber çekmeye geldik.')
style(163,"Evet! Şu sıralar çok popüler olan GNN'deniz.\nTim, kolye olayındaki gibi bize de\nyardım eder misin?",'“Süper popüler” ve “şu kolyede yaptığın gibi” doğal konuşma değildi; bilgi kaybetmeden yeniden kuruldu.','JP 今をときめくGNN ile FR/DE/IT/ES GNN’nin popüler/gözde kanal olduğunu ve Tim’den kolye olayındaki gibi yardım istendiğini doğruluyor.')
critical(164,'Meiko, yapma!\nOnları da buna bulaştıramazsın...','“Onları sürükleyemezsin” Türkçede fiziksel sürükleme gibi anlaşılıyordu; Emilia, Meiko’nun Tim ve Pikachu’yu yine tehlikeli işe karıştırmasına itiraz ediyor.','JP また無茶言って “yine olmayacak şeyler isteme”; FR “Laisse-les”, ES “Qué cosas dices” bağlamı destekliyor.')
style(167,'Hey, Pikachu! Ne yapıyorsun?\nAcele et, yoksa Drifblim gider.','“Yoksa gidecek” öznesiz ve belirsizdi; sahnede ayrılacak olan Drifblim.','JP 早くしないと行っちゃうよ ve sahne akışı Drifblim ile çıkış hazırlığını doğruluyor.')
style(173,'*ıkınır*','EN “grunt” ve JP よ！ burada Pikachu’nun fiziksel olarak Tim’in omzuna çıkma eforu; “homurdanır” kızgınlık sesi değildi.','Sahne eylemi ve EN/JP ünlemi fiziksel eforu destekliyor.')
style(174,'*inler*\nOmzuma çıkmak istediğini\nsöyleyebilirdin.','Tim’in ilk sesi fiziksel ağırlığa tepki/groan; “homurdanır” yanlış duygu. Cümle de gereksiz dolgu olmadan doğal Türkçeye çekildi.','EN groan, JP なに！？ ve FR/DE/IT/ES Pikachu’nun omza çıkmak için istemesi gerektiğini doğruluyor.')
style(175,'Öyle hiç eğlencesi kalmaz!\nHadi, Drifblim!\nSana güveniyoruz.','“Bu hiç eğlenceli değil” bağlamda ters/katı kalıyordu; Pikachu, önceden izin istemenin eğlenceyi bozacağını söylüyor.','EN “That’s no fun!”, FR/IT/ES “öyle olsaydı eğlencesi olmazdı/daha eğlenceli böyle” anlamını doğruluyor.')
sound(176,'Pokémon sesi (Anlaşıldı)')
sound(177,'Pokémon sesi (Hadi gidiyoruz!)')
style(186,'Ay! Tavanda bir açıklık var.\nUçabilen bir Pokémon bizi yukarı taşıyabilir.','“Tavan açık / bir uçan Pokémon” mekanik Türkçeydi; açık geçit ve uçabilen Pokémon fikri doğal biçimde kuruldu.','JP 吹き抜け, DE Loch in der Decke, IT apertura, ES agujero tavandaki açıklığı; tüm diller uçabilen Pokémonla çıkışı doğruluyor.')
style(187,'Evet. Buraya bir sürü Pokémon yerleşmiş;\nuçabilen biri de vardır mutlaka, değil mi?')
critical(189,'Doğru! İşi kapmaya başladın.\nBu karanlıkta aramak zor.\nÖnce nerelere bakacağımızı kestirelim.','“Etrafı tanımamız gerek” özgün “önce hedef/alan belirleme” anlamını tam vermiyordu.','JP 先に目星をつける, FR objectifs, DE/IT/ES aramayı yakın alan/hedeflere odaklama anlamında birleşiyor.')
style(193,'Şey... hangileriydi?')
style(194,'Meiko... Aklıma geldi!\nAz önce çektiğimiz görüntülere bakarsak\nburada hangi Pokémonların olduğunu anlayabiliriz.')
style(198,'Ha? Çantam yok!','“Yok olmuş” gereksiz gizem/eylem ekliyordu; Emilia çantayı bulamıyor.','JP ポーチが無い, FR/DE/IT/ES “çanta nerede/yok” anlamını doğruluyor.')

# 200-249
style(200,'Yedek pil onun içinde...','“Pili içinde” Türkçede eksik ve hangi pil olduğu belirsizdi; bağlam yedek batarya.','JP バッテリーはその中, FR/DE/ES yedek pil/bataryanın çantada olduğunu doğruluyor.')
style(208,'Teşekkür ettiğini söylüyor.')
style(209,'Tek bir Litwick’in alevi\nbuzu eritmeye yetmiyor gibi...','“Tek bir alev” özneyi belirsizleştiriyordu; tüm diller bir Litwick’in tek başına yetmediğini söylüyor.','JP 1匹の炎, FR une seule flamme, DE eines einzelnen Lichtel, IT/ES tek Litwick vurgusu.')
style(211,'Bunlar Noibat.')
critical(215,'Ne? Drifblim bir yana,\nyemek kokusu aldığınızı mı söylüyorsunuz?','Mevcut “Neyse, yemek kokusu mu alıyorsun?” hem tekil hitap hem de “Drifblim’i boş verip yemeğe odaklanma” şakasını kaybediyordu.','JP そんなことよりも食べ物の匂い, FR/DE/IT/ES Noibatların soruyu bırakıp yemek kokusuna odaklandığını doğruluyor.')
critical(216,'Ha? Aa! Cebimde bir şeker\nkalmış.','“Bir parça şeker” Türkçede madde şekeri gibi algılanıyor; nesne tek bir bonbon/şekerleme.','JP お菓子が1つ, FR bonbon, ES caramelo; IT caramelle. Tek parça şekerleme/bonbon anlamı.')
style(220,"Bu üçünün de söylediğine göre Drifblim\nkendi tünelindeymiş. Şekeri verirsek\ngeçmemize izin vereceklermiş.")
style(221,'Ne? Burada o kadar çok\nDrifblim mi var ki?')
term(222,'Yok, bence şekeri kapmak için yalan söylüyorlar.\nHangisinin doğru söylediğini anlamak için\n{{CTRL:0000:0003:FF4B4BFF}}ifadelerini toplayıp{{CTRL:0000:0003:FDFDFDFF}} doğrulayalım.','“Testimony” burada dedektiflik terminolojisinde “ifade”; “karşılaştırmak”tan öte ifadelerin doğruluğunu teyit etme/kanıtlama amacı var.','JP 証言を集めてウラをとる = ifadeleri toplayıp doğrulamak; FR témoignages, DE/IT/ES kanıt/ipuçlarıyla doğru söyleyeni belirleme anlamını destekliyor.')
style(224,'Hımm, bu soğukta nehre girmek\nölümcül olabilir. Başka türlü geçemez miyiz?','“Hayatı tehlike olur” dilbilgisel olarak bozuktu; tehlike düzeyi ve alternatif yol fikri doğal Türkçeye getirildi.','JP 命とり, EN life-threatening, FR/DE/IT/ES ciddi tehlike ve başka geçiş yolu arama anlamını doğruluyor.')
style(225,'Ha? Mağaranın içlerinden\nrüzgâr mı geliyor?','“arka tarafından” mağara mekânında yapaydı; 奥 = iç/derin kısım.','JP 奥から, FR/IT/ES fond/interior = mağaranın derinlerinden/içinden.')
style(228,'İşte çözümü düşünmek de\nişin eğlenceli yanı, değil mi?')
style(229,'Doğru ya. Büyük Dedektif’e yakışır cevap!\nO zaman {{CTRL:0000:0003:FF4B4BFF}}Drifblim’le{{CTRL:0000:0003:FDFDFDFF}} konuşup\n{{CTRL:0000:0003:FF4B4BFF}}Emilia ve Meiko’ya da{{CTRL:0000:0003:FDFDFDFF}} danışalım.','Mevcut replik İngilizce cümle yapısını mekanik izliyor ve kontrol kodu çevresinde gereksiz tire taşıyordu.','JP 名探偵だね＋相談してみよう; FR/DE/IT/ES Drifblim, Emilia ve Meiko ile konuşup danışma fikrini doğruluyor.')
critical(232,'Evet, bu kaynak suyuyla ünlü.\nKahve yapmak için de çok iyi.','“Bu su meşhur” eksik/garipti; suyun kaliteli/ünlü kaynak suyu olduğu söyleniyor.','JP 名水で有名, ES calidad de este manantial, FR pureté, DE mineral içeriği suyun niteliğiyle ününü doğruluyor.')
critical(233,'O hâlde Glalie’ye biraz su götürelim.','Mevcut “içecek bir şey bulalım” sanki başka içecek arıyormuş gibi; doğrudan nehir suyunu Glalie’ye götürüyorlar.','JP 汲んでいこう, FR/DE/IT/ES “bu sudan biraz götürelim” anlamını açıkça doğruluyor.')
style(242,'Şimdi karşıya geçebiliriz.\nAyağın kaymasın, dikkat et!')
critical(243,'Hadi bakalım...!','Mevcut “Şey, tamam!” fiziksel eylem öncesi ünlemi yanlış yorumluyordu.','JP よーし, FR “À la une, à la deux”, DE “eins, zwei”, ES “Manos a la obra” = işe koyulma/efor hazırlığı.')
style(245,'Hı? Bunlar Litwick olmalı.\nMemlekette de görmüştüm.','Mevcut tekil “bir Litwick” sahnedeki çoğul Pokémonları kaçırıyordu.','DE açıkça “zwei Lichtel”; FR/IT/ES çoğul Litwick/Funécire. JP tür adı bağlamda çoğul olabilir.')
style(246,'İyi fark ettin, Tim!\nHey, Litwick! Uyanın bakalım!','“Çok dikkatli, Tim” eksik övgü; ayrıca sahnede birden fazla Litwick’e çoğul sesleniliyor.','JP よく気づいたな; FR/DE çoğul “vous deux/ihr”; sahne iki Litwick gösteriyor.')

# Manual decisions, episode2 rows 250-599
style(251, "Aynen. Bunun için de önce\nbir çıkış yolu bulmamız gerek.", "JP/SC/TC and European localizations say first secure/find an exit; natural Turkish.")
style(259, "Bir sürü arkadaşı olduğu için\nburada çok eğleniyormuş.", "Pikachu is relaying Litwick's statement, not asking a question; all languages support statement reading.")
term(265, "Burada üç tür Pokémon yaşıyormuş.", "JP/FR/DE/IT/ES/Chinese all refer to three kinds/species of Pokémon; Turkish singular construction corrected.")
style(269, "İşe yarayacak bir şey biliyor musun?", "Natural question; EN 'anything useful', JP asks whether it knows anything useful.")
style(271, "Tabela mı? Kırık oluşu\ndikkatini çekmiş gibi.", "JP/European versions say Litwick is bothered/concerned that the sign is broken.")
style(274, "Mağaranın derinlerinde, yüksek bir yerdeki\nLitwickleri uyandırmak istiyoruz...", "Repairs split Turkish syntax while preserving JP/FR/DE/IT/ES meaning.")
style(276, "Sabah olunca uyanacaklarmış, öyle mi?\nHadi ama!", "Pikachu reacts to Litwick sleeping until morning; natural Turkish tone.")
style(281, "Böyle ilerlemeye devam ederiz umarım.", "Naturalizes awkward literal phrasing without changing meaning.")
style(283, "Daha güçlü bir ateşe ihtiyacımız var.", "All languages ask for/need stronger fire; concise natural Turkish.")
style(284, "Pikachu, burada bir Litwick var!", "Fixes deictic phrasing; Tim points out a Litwick present here.")
style(294, "Delikten görünen yıldızlar\nçok güzelmiş.", "JP and all localizations refer to stars visible through the opening.")
style(295, "Şu tavandaki açıklığı diyordur.\nBurası boşuna romantik bir buluşma noktası değil.", "Clarifies ceiling opening and preserves the romantic/date-spot joke supported across languages.")
term(299, "Litwickler soğuğu sevmediği için\nnehirden en uzak olan {{CTRL:0000:0003:FF4B4BFF}}en soldaki tünelde{{CTRL:0000:0003:FDFDFDFF}}\ntoplanıyorlarmış.", "JP 横穴 and other languages refer to the side tunnel; distinguishes it from the wall opening and preserves control codes.")
critical(305, "Hı? Kazmadan da mı çöküyor?\nAa, az önce kayaları düşürdüğümüzde\nsen de yakındaydın demek. Kusura bakma.\nÇarpmanın etkisiyle küçük, sert parçalar düşmüş.", "Current Turkish syntax/causality is broken; JP/FR/DE/IT/ES describe debris/small hard pieces falling from the impact when the rocks fell.")
style(306, "Seni de tehlikeye attık, ha?\nKusura bakma.", "Natural apology; speaker realizes their actions endangered the Pokémon.")
style(307, "Hımm, belki yere bir şey düşmüştür.", "Natural Turkish for checking whether something fell to the ground.")
style(309, "Mağaranın derinlerinde, yüksek bir yerdeki\nLitwickleri uyandırmaya çalışıyoruz...", "Repairs split syntax; same objective as other Litwick lines.")
term(313, "Bak! Şurada da Litwickler var!", "JP/Chinese and context indicate multiple Litwick; Turkish pluralized.")
term(315, "Uyanın!", "Addressing multiple sleeping Litwick; plural imperative.")
style(317, "Olmuyor. Sesimizi duymuyorlar.", "JP/European languages say calling out isn't working / they cannot hear them.")
critical(322, "Muhtemelen Drifloon'dan yardım istiyorlardır.", "Current Turkish reverses agency; JP/FR/DE/IT/ES say the Litwick likely ask Drifloon for help.")
style(325, "Mağaranın içleri de iyice aydınlandı.", "Natural Turkish for the interior becoming brighter.")
style(335, "Burada gerçekten bir sürü farklı Pokémon yaşıyor.", "Natural phrasing; all languages emphasize many different Pokémon living here.")
style(339, "Noibatlar sayesinde içeride\nhuzurla uyuyabiliyormuş.", "JP and localizations say it can sleep peacefully because Noibat keep watch/help.")
style(341, "Gerçi yemek görünce hemen tav oluyorlar...", "JP/DE/IT/ES explicitly note Noibat are easily lured/bribed by food/candy; natural humorous Turkish.")
style(344, "İşe yarayacak bir şey biliyor musun?", "Natural question; faithful to JP/EN.")
style(346, "Buralarda çeşit çeşit taş varmış.", "JP/European localizations mention many kinds of stones/rocks.")
style(348, "Önce bulduğumuz taşları toplayıp\nbirleştirmeyi deneyelim.", "Naturalizes instruction; gather/combine stones already found.")
style(350, "Mağaranın derinlerinde, yüksek bir yerdeki\nLitwickleri uyandırmaya çalışıyoruz...", "Repairs recurring split syntax.")
style(356, "Demek ileride nehir var...\nBurası mağaranın en derin yeri gibi.", "JP/FR/DE/IT/ES identify the river ahead and this as the deepest area.")
style(364, "Bir şey biliyor musun?", "Natural concise question.")
style(370, "Litwicklerin tünelini bulursak\ngerisi de çözülür belki.", "JP 横穴 / localizations refer to locating Litwick's side tunnel; terminology made consistent.")
style(373, "İşe yarayacak bir şey biliyor musun?", "Natural question.")
style(375, "Küçük taşlar işimize yarar mı, diyor.\nNehirde taş sektirmeyi seviyormuş.", "Pikachu relays Pokémon's suggestion; JP/European versions mention skipping small stones on the river.")
style(376, "Ben de babamla sık sık taş sektirirdim.", "Natural Turkish; Tim recalls skipping stones with his father.")
style(377, "Buralarda küçük taşlar görmüştüm.", "Naturalizes recall of small stones nearby.")
style(397, "Yorgunluğu hakkında", "UI topic label; natural nominal form.")
style(400, "Demek biraz toparladın.\nKendine geldiğinde kıpırdayamayacak haldeymişsin.", "JP/FR/DE/IT/ES: Glalie recovered somewhat but had been unable to move after regaining consciousness.")
term(418, "Diyor ki {{CTRL:0000:0003:FF4B4BFF}}Buz Işını{{CTRL:0000:0003:FDFDFDFF}} konusunda\nçok iyiymiş.", "Corrects move-name typo/wording; all languages identify Ice Beam proficiency; control codes preserved.")
term(419, "Ah, o saldırı... Gerçekten etkileyiciydi.\nBir şeye ihtiyacımız olursa senden yardım isteriz.", "Naturalizes praise and request while preserving meaning.")
term(425, "Buz Işını hakkında", "UI topic label corrected/standardized.")
term(426, "Glalie! Senden bir ricamız var.", "Natural request opener.")
term(427, "Hâlâ güçsüzken seni yormak istemem ama\nbize yardım edebilir misin?\nNehri geçmemiz gerekiyor.\nBuz Işını'yla nehri dondurabilir misin?", "JP/FR/DE/IT/ES ask weakened Glalie to freeze the river with Ice Beam; natural Turkish.")
style(433, "Başına düşen kaya epey sertmiş.", "Natural Turkish for the rock that struck it being hard/heavy.")
style(434, "Kusura bakma. O kaya tavandaki\naçıklığın yakınında düşmüştü, değil mi?", "Keeps ceiling-opening location and apology clear.")
term(435, "Evet! Litwickleri uyandırdık!", "Multiple Litwick; plural corrected.")
critical(442, "Demek Glalie'nin çılgına dönmesinin\nsebebi bir kavga değilmiş.", "JP/other languages establish it was not enraged because of a fight; natural Turkish inference.")
style(444, "Mağaranın derinlerinde, yüksek bir yerdeki\nLitwickleri uyandırmaya çalışıyoruz...", "Repairs repeated split syntax.")
critical(451, "Kendi tünelleri, Litwicklerin kullandığı\ntünelin hemen yanındaymış.", "Mevcut Türkçe bilgi vermek yerine yanlışlıkla görev hedefini tekrarlıyordu; Drifloon kendi yuvalarının Litwick tünelinin yanında olduğunu söylüyor.", "JP 自分たちはヒトモシが使う穴のとなりをねぐら; FR/DE/IT/ES ve iki Çince sürüm de Drifloonların Litwicklerin yanındaki tünelde yaşadığını açıkça doğruluyor.")
term(452, "{{CTRL:0000:0003:FF4B4BFF}}Drifloonların tüneli, Litwicklerin tünelinin yanında{{CTRL:0000:0003:FDFDFDFF}}.\nAnladım!", "JP/FR/DE/IT/ES locate Drifloon beside Litwick; consistent tunnel terminology; controls preserved.")
critical(453, "Litwicklerin hangi tünelde yaşadığını bulursak\nbir sürü şeyi çözebiliriz.", "Bu bir UI başlığı değil Pikachu repliğiydi; mevcut Türkçe neredeyse tüm cümleyi kaybetmişti.", "JP どの穴にヒトモシがいるかでいろいろとわかりそう; DE/IT/ES bunu çözümün anahtarı, ZH ise birçok şeyi açıklayacak bilgi olarak doğruluyor.")
style(457, "‘Kazma ne?’ diyor.\nGerçi Pokémonların pek işi olmaz zaten.", "Pikachu relays Pokémon not knowing what a pickax is; natural joke.")
style(463, "Bir şey biliyor musunuz?", "Addresses multiple Pokémon; plural polite form.")
style(468, "İşimiz zor.", "Natural concise reaction.")
critical(469, "Evet. Biraz daha bilgi toplarsak\nDrifblim’in yerini çıkarabiliriz.\nDiğer tünellerde kimlerin yaşadığını\nbulursak geriye kalan tünel\nDrifblim’indir, değil mi?", "Mevcut Türkçe beş cümlelik çıkarım mantığını tek bir soruya indirgemişti; bulmacanın eleme yöntemi kayboluyordu.", "JP ve EN, diğer tünellerde yaşayan Pokémonlar belirlenirse kalan tünelin Drifblim’e ait olacağını açıkça kuruyor; FR/DE/IT/ES de eleme yöntemini doğruluyor.")
critical(470, "Anladım... Demek diğer Pokémonların\nhangi tünellerde yaşadığını öğrenmek de önemli.", "Mevcut Türkçe yanlış görev hedefi veriyordu; Tim burada Pikachu’nun eleme mantığını kavrıyor.", "JP ほかのポケモンがどの穴にいるのかも大事; FR/DE/IT/ES ve ZH diğer Pokémonların hangi tünelde olduğunun önemli olduğunu doğruluyor.")
style(474, "Son zamanlarda insanlar gece gündüz gelip gittiği için\nrahat uyuyamadığını söylüyor.", "JP/FR/DE/IT/ES: frequent visitors day and night have disturbed its sleep.")
style(484, "İnsanlar buraya gelmeye başladığından beri\ntürlü sıra dışı yiyecekler tatma fırsatı buluyorlarmış.", "JP/localizations: visitors brought opportunities to taste unusual foods.")
style(489, "Hiçbir şey yokmuş. İnsanların burada bıraktığı çöpleri\nmağaradaki Pokémonlar hemen topluyormuş.", "JP/European languages say Pokémon promptly clean up human litter; repairs awkward syntax.")
style(494, "Anladım. Burası canlandıkça\ntürlü insanı izlemek hoşuna gidiyor demek.", "Naturalizes Pokémon enjoying watching varied visitors as cave becomes lively.")
style(499, "Bir tane daha şeker verirsek\nbilgiyi söyleyecekmişsin, öyle mi?", "JP/European localizations: Noibat demands another candy in exchange for info; natural Turkish.")
style(500, "Şekeri mi diyorsun?\nBaşka kalmadı.", "Natural response; candy supply exhausted.")
style(501, "Yemek koparmaya çalışıyor işte.\nAldırma.", "Pikachu recognizes Noibat is angling for food; natural tone.")
style(516, "Bu rüzgârla yeterince yükselemiyormuş.\nBizi buradan çıkarması için {{CTRL:0000:0003:FF4B4BFF}}güçlü bir rüzgâr{{CTRL:0000:0003:FDFDFDFF}} gerekiyor.", "JP/FR/DE/IT/ES: Drifblim needs stronger wind to rise/carry them; control codes preserved.")
style(518, "Bir yolunu buluruz.\nÇıkışa iyice yaklaştık, orası kesin!", "Natural encouragement; preserves nearing escape.")
style(533, "İnsanların kullandığı aletlerden\npek anlamıyor galiba...", "JP/localizations: Pokémon doesn't understand human tools well.")
style(537, "Bu kayalar Glalie'nin az önceki\nsaldırısıyla mı çöktü acaba?", "Natural causal question.")
style(538, "Evet, fena kudurmuştu.", "Natural colloquial description of Glalie rampaging.")
style(539, "Sanki kendini tamamen kaybetmişti.", "JP/European localizations: it seemed to have lost control of itself.")
style(543, "Buldum! Çanta burada.", "Natural discovery line.")
style(547, "Bir şey olmaz. Böyle kalırsa\nmağaranın yeni gözdesi bile olur!", "Preserves humorous idea it could become a new attraction/famous feature.")
style(549, "Hımm, demek buzu eritmemiz gerek.\nTim, şunu kucağına al.", "JP says they need to melt ice and asks Tim to lift/carry it; natural Turkish.")
style(555, "Her neyse, önce buradan çıkalım.\nEmilia ve Meiko'nun yanına dönelim.", "JP Emilia-tachi and FR/DE/IT/ES refer to Emilia and the others/girls, not Emilia alone.")
style(558, "Oo, bu iyi! Duvarı kırıp deliği genişletirsek\nrüzgâr daha güçlü eser.", "Naturalizes plan; wall opening is deliberately distinguished from side tunnels.")
style(560, "Evet. Sence bunu nasıl yapabiliriz?", "Natural question; removes machine-like phrasing.")
style(563, "Glalie'den yardım iste", "Choice text: ask Glalie for help, supported across languages.")
style(571, "Doğru ya. Çevreyi baştan beri\ndikkatle inceliyorsun, değil mi Pikachu?", "Natural Tim acknowledgement; Pikachu has been observing surroundings.")
style(572, "Elbette. Büyük dedektifim sonuçta.\nBuradaki malzemelerle yapabileceğimiz tek bir alet var.", "Restores Pikachu's boastful voice and deduction.")
critical(573, "Neymiş o?", "Current 'Ne oldu?' asks what happened; JP/EN ask what the tool/item is.")
style(582, "Arayayım. Başka ne gerekiyor?", "Natural Tim response to searching materials.")
style(584, "Biraz da uzun olsun. Böylece savurma gücü artar,\nkazmak kolaylaşır.", "JP/European versions explain a long handle makes digging easier through leverage/swinging force; natural Turkish.")
style(590, "Bu hava deliğini genişletmemiz gerek.", "Natural concise objective; this is the wall/air opening, not Pokémon side tunnel.")
critical(591, "Evet, duvarı kazmayla kırmamız gerek.\nNe gerektiğini unutursan notlarına bak.", "Mevcut v17 taslağı ikinci cümleyi tamamen düşürmüştü; oyun içi yönlendirme bilgisi kayboluyordu.", "JP 必要なものがわからなくなったらメモを確認; EN ve FR/DE/IT/ES de malzemeleri unutursa notlara bakmasını söylüyor.")
term(592, "Belki yön tabelasıydı. Kırılmış; yalnız direği kalmış.", "FR/DE/IT/ES identify a signpost/stake; 'direk' is the material for a pickax handle, not generic 'sopa'.")
term(593, "Bu direği kazmanın sapı olarak kullanabiliriz.", "Consistent material terminology; signpost becomes pickax handle.")
style(599, "Bu taş... Mavisi çok güzel ama ne kadar sert acaba?", "Natural observation; asks whether the blue stone is hard enough for the pickax head.")

# Manual decisions, episode2 rows 600-939
style(604,"Böyle zamanlarda kafanı kullanacaksın.\nIşık verecek bir şey yok mu?", "JP/FR/DE/IT/ES/Chinese all frame this as 'use your head' and look for something that can provide light; natural Pikachu tone.")
style(607,"Glalie neden birdenbire\nçılgına döndü acaba?", "JP/DE/IT and Chinese ask why Glalie suddenly went berserk/lost control; current 'attacked us' is narrower than the common meaning.")
critical(617,"Zavallı... hâlâ buzun içinde.","Current 'hâlâ öyle' is ambiguous and drops what is still true.","JP 今もまだ凍ってる, FR/DE/IT/ES and both Chinese explicitly say the Pokémon is still frozen/in the ice.")
style(618,"Glalie'ye ne oldu böyle?", "Natural Turkish; all languages ask what happened to Glalie.")
style(620,"Kaçmaktan çok, savrulup gitmiş gibi.", "JP/FR/DE/IT/Chinese distinguish escaping from being blown/knocked away; natural Turkish.")
style(651,"Evet, böyle durduğum sürece acımıyor.\nAma yine sana yük oluyorum, Tim.", "JP/FR/DE/Chinese emphasize Emilia relying on/troubling Tim again; current 'başınıza iş açıyorum' is harsher and pluralizes the addressee.")
critical(653,"İşte Emilia'ya kendini gösterme fırsatı, ha Tim?","Current Turkish turns Pikachu's teasing into a generic reliability statement and loses the flirtatious joke.","JP いいとこ見せないとな, DE/IT 'show what you're made of / make a good impression', FR/ES use prince-charming imagery; all support teasing Tim about impressing Emilia.")
critical(654,"Benimle dalga geçme.","Current 'Neyden bahsettiğini bilmiyorum' follows the freer English line but misses Tim's actual reaction.","JP からかわないで, FR/IT 'stop teasing me', ES 'stop that nonsense'; Chinese also says 'don't make fun of me'.")
style(669,"Tamam, Tim. Görüntüleri inceleyelim.\nUçabilen Pokémonları gözden kaçırma.", "JP/FR/DE/IT/ES/Chinese specifically tell Tim to watch for Pokémon capable of flying; removes awkward 'karşı gözünü dört aç'.")
term(672,"Bizi taşıyabilirse tavandaki\naçıklıktan çıkabiliriz!", "JP 吹き抜け, DE/IT/ES/Chinese all describe an opening in the ceiling; 'delik' is less precise and inconsistent with the cave terminology.")
style(677,"Evet. Bir de sap ve ip gerekiyor.", "All languages list a handle and rope as needed pickax materials, not merely optional things that 'could be used'.")
style(679,"Olur! İstemek zorunda kaldığım için kusura bakma.\nSeninki benim kemerimden daha ince;\ndaha iyi iş görür. Çok teşekkür ederim.", "Clarifies that Emilia's belt is thinner than Tim's and thus better suited; all official languages support this comparison.")
style(680,"Tim! Rüzgâr güçlendi.\nDemek başardın!", "JP/FR/IT/ES/Chinese credit Tim for the stronger wind; natural praise without English-heavy wording.")
style(683,"Ben de biraz övgü alsam\nfena olmazdı.", "Pikachu wants some praise too; natural boastful tone.")
style(685,"Oo? Kalplerimiz bir mi oldu ne?", "JP/Chinese use hearts/mutual understanding while FR/DE/IT/ES use mind-reading; playful Turkish localization preserves the joke.")
style(688,"Teşekkürler. Burada hiç görmedim;\nbelki mağaranın daha derinlerindedir.", "JP/FR/DE/IT/ES/Chinese express possibility rather than certainty; current 'demek ki' overstates it.")
critical(695,"İlerisi tehlikeli olabilir.\nKendini zorlama, olur mu?","Current plural 'Lütfen dikkatli olun' is wrong for Emilia speaking to Tim and weakens the specific warning not to overdo it.","JP 無理しないで, DE 'kein unnötiges Risiko', ES 'no hagas ninguna locura', Chinese 'don't force yourself'.")
critical(699,"Yaklaşık 5 metre gibi.","The English localization converts the value to 'more than 16 feet'; current Turkish then incorrectly says more than 5 metres.","JP says about 5 metres; FR/DE/IT/ES and both Chinese also give approximately 5 m. Turkish should use the metric value shared by the non-English localizations.")
style(701,"Ben daha çok kafa adamıyım;\nspor bana göre değil.", "JP 頭脳派 and all European localizations contrast intellect with athletics; natural Pikachu voice.")
term(702,"Çekim yaparken burası aydınlıktı.\nLitwicklerin alevleri etrafı aydınlatıyordu.", "FR/DE/IT/ES indicate multiple Litwick; plural Turkish makes the scene clearer.")
style(707,"Belki bir gün seni şehrin büyük dedektifi diye\nröportaja alırım.", "JP says interview Tim as the city's great detective; FR/IT/ES creatively frame it as a future famous-detective interview. Natural Turkish preserves the tease.")
style(720,"Aslında fikir patronumdan çıktı.", "All languages say the idea/proposal came from Meiko's boss; removes English filler 'ama yine de'.")
style(725,"Pokémonların çılgına dönme sebebi hakkında", "Repairs awkward Turkish topic label; JP/FR/DE/IT/ES all label the cause of Pokémon going berserk/aggressive.")
term(729,"Ama bizim açımızdan iyi oldu;\nbundan özel haber çıkar.", "JP スクープ, FR/IT/ES scoop/primicia and Chinese 独家新闻 mean an exclusive/scoop; standardized as 'özel haber'.")
style(730,"Her şeye de iyi tarafından bakıyorsun...", "Natural Pikachu reaction to Meiko's extreme optimism; shared across languages.")
style(737,"Sana güveniyorum! Videodan nereye\ngittiğini anlayamıyorum.", "JP/FR/DE/IT/ES/Chinese say the footage doesn't reveal where Drifblim went; 'seçemiyorum' is unnatural/wrong verb.")
style(738,"Yine de bu mağarada olduğunu\nöğrenmek bile kazanç.", "JP 収穫 and other languages say simply knowing it is in the cave is already useful/a gain.")
critical(742,"Çoğu mağarada dışarı açılan küçük açıklıklar olur;\nbazen rüzgâr oralardan içeri eser.","Current 'gizli geçitler' implies traversable secret passages, which is not the shared physical meaning in this cave puzzle.","JP 抜け穴, FR brèches, DE kleine Öffnungen, IT aperture, ES oquedades and Chinese 缝隙 all point to small openings/cracks that let air through.")
term(743,"Ama bu açıklıklar türlü sebeplerle\ntıkanabiliyor.", "Keeps the same 'small opening/crack' concept from the preceding line; all languages say such openings can become blocked.")
term(744,"Anladım! O açıklıklardan\nbirini bulursak—!", "Maintains the cave airflow-opening terminology; JP/Chinese refer back to those openings.")
style(745,"Evet. Böylece daha güçlü\nbir hava akımı oluşturabiliriz.", "Natural Turkish for creating/obtaining a stronger airflow; common meaning across localizations.")
critical(750,"Tabii ki kötü fikir—donarsın!\nBöyle mağaralardaki nehir suyu\nbuz gibidir.","Current Turkish begins 'Tabii ki soğuk', incorrectly answering a different question; Meiko is saying swimming is obviously a bad idea because Tim would freeze.","JP 当たり前だよ 凍えちゃう, FR/DE/IT/ES and Chinese all reject swimming and explain the cave river is extremely cold.")
critical(755,"Evet... Ben de iki aydır\nburaya uğramamıştım.","The English localization redistributes apartment-sharing information across the next line, but JP and both Chinese versions put the two-month absence here. This sequencing is clearer with the original scene timing.","JP オレも2ヶ月ぶり, SC/TC likewise say Pikachu has not been here for two months; European versions retain the shared-apartment idea across this exchange.")
critical(757,"Harry'yle burayı paylaşırdık.\nKazadan beri dedektiflik bürosunda kalıyorum.","Current line contains the typo 'Paylasiyorduk' and repeats the two-month absence while omitting the original-Japanese fact that Pikachu has lived at the agency since the accident.","JP 事故以来 事務所に住んでる, SC/TC same; EN/FR/DE/IT state that Pikachu and Harry shared the apartment. Turkish combines both non-conflicting facts across the exchange.")
style(769,"Tamam!", "Natural Turkish acknowledgement; JP/FR/DE/IT/ES all use a straightforward yes/OK.")
style(775,"Tamam...\nBen nasıl oldu da buna{{CTRL:0001:0006:}}\nrazı geldim?", "Current 'kendimi buna ikna ettirdim' is unidiomatic; JP/FR/Chinese say Tim feels he has been talked/dragged into it.")
style(776,"Baker, babamın bir Pokémon olayını\naraştırdığını söylemişti, değil mi?", "Naturalizes broken interrogative syntax while preserving the case-investigation information.")
style(783,"İyi iş, Tim.\nArtık Harry'nin izini sürebileceğiz!", "JP says the notes should let them trace Harry's movements; natural detective phrasing.")
critical(784,"Evet.","Current 'Hımmm...' follows the English hesitation but conflicts with the response used in most other localizations.","JP うん, FR Oui, DE Ja, ES Sí, Chinese 嗯 all give an affirmative acknowledgement; only EN is 'Hmmm'.")
style(787,"Bu şekil... Ryme Şehri'nin haritası bu.\nŞu işaretli yerler de Harry'nin\naraştırdığı olayların yaşandığı noktalar!", "Repairs machine-like 'bu çizim bu bölgenin düzeni' while preserving map and incident-location deduction.")
critical(798,"Bu ne?","Current 'Ne oldu?' means 'what happened?' and is the wrong question for Tim looking at an object.","EN/JP/FR/DE/IT/ES/Chinese all ask 'What is this/it?'.")
term(799,"Şey... tam olarak bilmiyorum.\nBelki kırık bir ampul parçası?\nAma böyle bir şeyin mağarada\nne işi var, değil mi?", "Western localizations identify a vial/flask; later JP explicitly identifies it as アンプル. 'Ampul parçası' matches terminology standardized in earlier manual episode-note reviews.")
term(803,"Hımm... Eğer bu bir ampul parçasıysa...\nEczaneler ve hastaneler şüpheli olabilir.\nAraştırma tesisleri de!", "JP アンプル, DE Ampulle and the other Western vial/fiala/vial terms point to the small medical ampoule; standardized Turkish terminology.")
style(804,"Pikachu, yalnız hastaneleri kontrol etsek bile\nbu iş bitmek bilmez!", "Naturalizes 'sonsuz sürer'; all languages emphasize the huge number/time burden.")
style(806,"O zaman aramayı daha da daraltmalıyız.\nAa! Tim, Harry'nin kazayı geçirdiği yeri\nharitada işaretler misin?", "Repairs awkward 'kazaya karıştığını' and keeps the narrowing-search deduction.")
style(814,"Hım, haklı olabilirsin!\nSırada burayı araştıralım.{{CTRL:0001:0006:}}", "Current word order 'araştırmalıyız sonra' is unnatural; same next-destination meaning preserved with the embedded control token.")
term(820,"Acaba çamaşır yıkamaya mı hazırlanıyordu?\nSepete gömlekler ve iç çamaşırları tıkıştırılmış.", "JP シャツ, FR chemises, DE Hemden and context indicate shirts; current 'tişörtler' is unnecessarily specific.")
critical(827,"Deseni güzel, dokusu da hoş.\nBu halıyı ben de sevdim.","Current Turkish contains the typo/nonword 'döküşü' and awkward phrasing.","JP 手触り, FR toucher, DE flauschig, IT morbido, ES textura and Chinese 触感 all refer to the carpet's feel/texture.")
term(829,"Fişler, bir not defteri, biraz şekerleme...", "JP お菓子, DE Süßigkeiten, IT dolcetti and Chinese 点心: standardized 'şekerleme' rather than generic 'tatlı'.")
term(830,"Anlaşılan harcamalarını kaydediyormuş.\nBöyle işlerde insanın canı şekerleme ister tabii.", "Keeps expense tracking and sugar/sweets joke natural; terminology standardized.")
critical(831,"Fişlerin altında da... anahtar yok.","Current 'fişler anahtara benzeyen hiçbir şeyi örtmüyor' is an unnatural literal misparse.","JP says no key behind/under the receipts; FR/DE/IT/ES/Chinese likewise explicitly check underneath them.")
style(836,"Hi-Hat Kafe'den.\nOrada kahve çekirdeği de satıyorlar.", "Correct source/directional case; receipt is from the café, and it sells beans.")
style(840,"Anahtarı buzdolabında mı saklamış acaba?\n...Yok.", "Naturalizes the little joke; JP/FR/IT/Chinese explicitly check whether the key was kept/chilled in the fridge.")
critical(841,"Plaklar, dergiler ve kitaplar\nkarmakarışık doldurulmuş.\nHım? Şu dolap kapağı açılmıyor...","This object has a lockable door, so calling it only a 'raf' creates a physical inconsistency.","JP 棚＋扉, FR/DE/IT/ES consistently use placard/Schrank/armadio (cabinet) and refer to its door. Turkish should use 'dolap'.")
term(842,"Kilitli gibi. Şüpheli.\nAnahtarı buralarda olmalı.", "Continues the lockable-cabinet context; natural Turkish.")
term(843,"Açılmıyor. Anahtar şart gibi.", "Natural continuation of the locked cabinet sequence.")
term(844,"İçinde ne var acaba?\nAnahtarı bulalım.", "Natural cabinet context; shared meaning across all languages.")
term(845,"Bir televizyon... Babam yalnızca haber izlerdi.\nBurası da eşya dolu: sözlük, romanlar,\nyemek dergileri, bolca şekerleme...", "JP お菓子 / FR bonbons / DE Süßigkeiten / IT dolcetti / ES caramelos; standardized 'şekerleme'.")
style(846,"Televizyon tamamen kapatılmış.\nPek izlemiyordu demek.", "JP says main power was off; FR/DE/IT say unplugged/disconnected. Common implication is it was deliberately fully powered down and rarely used.")
style(863,"Harry'nin evdeki alışkanlıkları", "UI choice label made natural and explicit; JP/FR/DE/IT/ES all refer to Harry's behavior/habits at home.")
style(864,"Babam evdeyken neler yapardı acaba...", "Natural reflection; fixes awkward tense.")
style(873,"Ben olsam nereye saklardım diye düşündüm.", "Current phrasing sounds like Tim is planning a present hiding place; all languages describe imagining where he would hide it.")
style(877,"Bir kutu kurabiye. İçindekiler...\nbayatlayıp yumuşamış.", "The cookies are stale/soggy from being open for months, not literally wet; JP ふにゃふにゃ and Western localizations support softened/stale texture.")
style(879,"Kutu açık; yarısı yenmiş gibi.\nAnahtar... burada değil.", "JP/IT/Chinese explicitly indicate the chocolate was partly eaten; natural Turkish.")
style(880,"Bitter çikolata, ha?\nHarry'yle zevkimiz aynıymış.", "Natural Turkish for bitter/dark chocolate and shared taste.")
style(881,"Kahve çekirdeği aldığı fiş.", "Fixes unnatural 'aldığı zamandan bir fiş'; all languages identify a receipt for coffee beans.")
style(883,"Belki anahtarı buraya saklamıştır—\nYok, burada da değil.", "Natural search reaction.")
style(888,"Buraya saklasa yanlışlıkla yakabilirdi.\nİyi bir yer değil.", "Naturalizes second-person conditional that incorrectly sounded like Tim hid it; all languages explain fire/heat risk.")
style(891,"Bu kavanozda babamın en sevdiği şekerler var.\nDoğum gününde ailece almıştık.\nBulmak için bir sürü mağaza dolaşmıştık.", "Naturalizes the memory while preserving favorite candy, birthday gift and difficulty finding it.")
style(892,"Doğru, pek sık rastlanmıyor.\nHadi, bir tane ver.", "Pikachu asks for one candy; playful demanding tone preserved.")
style(893,"Yine kafana göre— Hı?\nKavanozun altında bir şey var...", "Current past-tense 'bencilce davranmış' misreads Tim's interrupted scolding; all languages have Tim start objecting, then notice something beneath the jar.")
term(895,"Tabii! Saklamak için gerçekten iyi bir yer.\nHadi, şu dolabın kapağını açalım.", "FR/DE/IT/ES and JP door/cabinet context confirms lockable cupboard rather than 'raftaki kapaklar'.")
critical(909,"Drifblim'i bulmamız gerek.\nMağaranın {{CTRL:0000:0003:FF4B4BFF}}daha derinlerini{{CTRL:0000:0003:FDFDFDFF}} araştıralım.","Current 'mağaranın daha derine in kısmına' is grammatically broken.","JP 奥の方, FR fond, DE weiter drinnen, IT/ES and Chinese all mean deeper inside the cave; controls preserved.")
style(912,"Mağaranın daha derinlerini araştıralım.\nBunun için başka {{CTRL:0000:0003:FF4B4BFF}}Litwickler{{CTRL:0000:0003:FDFDFDFF}} bulup\nortamı aydınlatmamız gerek.", "Naturalizes purpose; Litwick provide light so exploration can continue.")
style(913,"Arkadaki Litwickler, biri yanlarına gelip\nseslenirse uyanmalı.\n{{CTRL:0000:0003:FF4B4BFF}}Drifloon{{CTRL:0000:0003:FDFDFDFF}}'dan yardım isteyelim mi?", "Natural Turkish suggestion; preserves close-range waking condition.")
critical(914,"Litwickler sayesinde mağaranın\n{{CTRL:0000:0003:FF4B4BFF}}daha derinlerini{{CTRL:0000:0003:FDFDFDFF}} araştırabiliriz.\n{{CTRL:0000:0003:FF4B4BFF}}Başka Pokémonlar da olabilir{{CTRL:0000:0003:FDFDFDFF}};\ngözünü dört aç!","Current Turkish says there 'definitely' are more Pokémon, stronger than the original.","JP かもしれん and FR/IT/ES/Chinese all express possibility ('may/might be other Pokémon'), not certainty.")
term(916,"{{CTRL:0000:0003:FF4B4BFF}}Vaka Notları'nı{{CTRL:0000:0003:FDFDFDFF}} açıp\nbu problemi çözelim!", "Preserves the Case Notes UI term and fixes awkward control-code line break.")
style(918,"Nehri nasıl geçeceğiz acaba...\n{{CTRL:0000:0003:FF4B4BFF}}Emilia ve Meiko'ya{{CTRL:0000:0003:FDFDFDFF}}, bir de {{CTRL:0000:0003:FF4B4BFF}}Drifblim'e{{CTRL:0000:0003:FDFDFDFF}}\ndanışalım mı?", "DE names Emilia and Meiko; JP/FR/IT/ES/Chinese say the ladies plus Drifblim. Natural Turkish consultation phrasing.")
style(920,"Mağaranın derinlerinden su kokusu geliyor.\nArkadaki {{CTRL:0000:0003:FF4B4BFF}}Litwicklerden{{CTRL:0000:0003:FDFDFDFF}}\nbize ışık vermelerini isteyelim.", "JP/EN describe sensing the river by smell; IT/ES adapt to sound. 'Su kokusu' is more natural Turkish while keeping original sensory clue.")
style(926,"{{CTRL:0000:0003:FF4B4BFF}}Glalie{{CTRL:0000:0003:FDFDFDFF}}'den nehri\ndondurmasını isteyelim.", "Fixes broken Turkish case construction; all languages give the same instruction.")
style(928,"Kazma yapmak için kullanabileceğimiz\nmalzemeleri arayalım.\n{{CTRL:0000:0003:FF4B4BFF}}Yerde{{CTRL:0000:0003:FDFDFDFF}} bir sürü şey vardı.", "Naturalizes material-search instruction and removes duplicate spacing.")
style(929,"Gidip {{CTRL:0000:0003:FF4B4BFF}}Emilia'ya{{CTRL:0000:0003:FDFDFDFF}} danışalım.\nBelki kazma malzemeleri konusunda\nbir fikri vardır.", "JP explicitly says consult Emilia about pickax materials; natural Turkish.")
term(931,"Evet! Kazmamız hazır!\nHadi {{CTRL:0000:0003:FF4B4BFF}}arkadaki duvarın{{CTRL:0000:0003:FDFDFDFF}}\naçıklığını genişletelim.", "JP/DE/IT/ES describe digging/enlarging the wall opening; avoids suggesting they tunnel through the entire wall.")
style(932,"Şimdi çıkabiliriz!\n{{CTRL:0000:0003:FF4B4BFF}}Drifblim{{CTRL:0000:0003:FDFDFDFF}}'den bizi buradan\nçıkarmasını isteyelim.", "Natural request; all languages ask Drifblim to carry/get them out.")
term(933,"İpucu arayalım.\nYatağın yanındaki {{CTRL:0000:0003:FF4B4BFF}}dolapta{{CTRL:0000:0003:FDFDFDFF}} bir şey var mı?", "FR/DE/IT/ES use cabinet/armoire and the object is lockable; 'dolap' fixes the physical mismatch.")
term(934,"İpuçlarını ararken dolabın anahtarını da\narayalım. Bakılacak diğer yerler:\n{{CTRL:0000:0003:FF4B4BFF}}TV{{CTRL:0000:0003:FDFDFDFF}}, {{CTRL:0000:0003:FF4B4BFF}}mutfak{{CTRL:0000:0003:FDFDFDFF}} ve {{CTRL:0000:0003:FF4B4BFF}}masanın{{CTRL:0000:0003:FDFDFDFF}} çevresi.", "Cabinet/key terminology made consistent; preserves all three suggested search areas and control codes.")
term(936,"Anahtarı bulduk.\nHadi şu {{CTRL:0000:0003:FF4B4BFF}}dolabı{{CTRL:0000:0003:FDFDFDFF}} açalım!", "FR/DE/IT/ES explicitly call this a cupboard/cabinet; consistent with the lockable-door sequence.")
style(937,"Ah, unutmadan...\nBugün topladığımız bilgilerden özellikle önemli\nolanları {{CTRL:0000:0003:FF4B4BFF}}Vaka Listesi'nde{{CTRL:0000:0003:FDFDFDFF}}\n{{CTRL:0000:0003:FF4B4BFF}}ayrı bir sayfaya{{CTRL:0000:0003:FDFDFDFF}} yazmalısın.", "Natural Turkish order while preserving both highlighted UI concepts and all information.")
style(939,"Hey, aferin! Şimdiden düşünmüş olman güzel.\nÖnemli bilgileri unutmamak için notlarını\nara sıra gözden geçir. Bundan sonra da\nönemli şeyleri böyle düzenli tut.", "Naturalizes awkward 'ileri görüşlü düşünmene' and keeps review/organization advice shared by all languages.")

critical(638, "Arada 5 metre var. Kaçırırsak\ndoğruca buz gibi nehre düşeriz.", "İngilizcedeki feet dönüşümü Türkçede “5 metreden daha geniş” diye gereksiz belirsizleşmişti; özgün Japonca doğrudan 5 metre diyor.", "JP 5メートル; FR/DE/IT en az 5 metre, ES ve iki Çince sürüm doğrudan 5 metre veriyor. Metrik Türkçede 5 metre esas alındı.")
term(467, "Anlaşılan bu üç tünelin her birinde\n{{CTRL:0000:0003:FF4B4BFF}}farklı Pokémonlar yaşıyor{{CTRL:0000:0003:FDFDFDFF}}.\nAma şu Noibatların her biri Drifblim’in\nkendi tünelinde olduğunu söylüyor.", "Anlam doğruydu ancak renkli vurguya bağlanan cümle tek satırda aşırı uzuyordu; üç tünel/üç farklı Pokémon mantığı daha okunaklı biçimde yeniden satırlandı.", "JP üç 横穴 içinde farklı Pokémonların yaşadığını ve her Noibat’ın Drifblim’in kendi tünelinde olduğunu söylediğini doğruluyor; FR/DE/IT/ES aynı yapıyı koruyor.")
style(586, "Doğru, son olarak {{CTRL:0000:0003:FF4B4BFF}}iki parçayı{{CTRL:0000:0003:FDFDFDFF}}\n{{CTRL:0000:0003:FF4B4BFF}}birbirine bağlayacak{{CTRL:0000:0003:FDFDFDFF}} bir şey gerek.\nİp olsa mükemmel olur.", "Anlam doğruydu fakat ikinci satır oyun metni için gereksiz uzundu; bilgi ve vurgu kodları korunarak okunabilir satırlara bölündü.", "JP ve EN son parçanın iki parçayı bağlayacak ip olduğunu, FR/DE/IT/ES de aynı işlevi doğruluyor.")
style(917, "Drifblim'in daha yükseğe uçması için\ngüçlü bir rüzgâr gerek.\n{{CTRL:0000:0003:FF4B4BFF}}Mağaranın derinlerinden{{CTRL:0000:0003:FDFDFDFF}}\ngelen esintiyi hissediyor musun?", "Mevcut anlam doğruydu ancak son satır aşırı uzundu ve renkli ifadenin başındaki küçük harf doğal değildi; kontrol kodları korunarak yeniden satırlandı.", "JP 奥の方 ve FR/DE/IT/ES mağaranın derinlerinden gelen esintiyi soruyor; bilgi değişmedi.")
style(371, "Peki, hangi tüneller Litwick'e,\nhangileri Drifloon'a ait...", "Anlam doğruydu fakat tek satır gereksiz uzundu; soru/çıkarım doğal iki satıra bölündü.", "JP, FR/DE/IT/ES Litwick ve Drifloon’un hangi tünellerde yaşadığını sorguluyor; bilgi değişmedi.")
style(504, "Geçebileceğimizi söylüyor.\nDrifblim'i çağırmaya gidiyorum; sen burada bekle.", "Anlam doğruydu ancak ilk satır uzun kalıyordu; Pikachu’nun yönlendirmesi daha okunaklı biçimde yeniden satırlandı.", "JP/DE/IT/ES geçiş izni alındığını, Pikachu’nun Drifblim’i çağırmaya gidip Tim’den beklemesini istediğini doğruluyor.")
style(821, "Yaklaşık bir haftalık çamaşır var burada.\nDemek çamaşır yıkamaya bile vakti olmamış.", "Mevcut Türkçe doğruydu ancak ilk satır yapay ve uzundu; doğal gözlem cümlesiyle kısaltıldı.", "JP 1週間ぶん ve FR/DE/IT/ES/ZH yaklaşık bir haftalık kirli çamaşır ve Harry’nin yıkamaya vakit bulamamasını doğruluyor.")
style(924, "{{CTRL:0000:0003:FF4B4BFF}}Glalie{{CTRL:0000:0003:FDFDFDFF}}'yi kontrol edelim;\n{{CTRL:0000:0003:FF4B4BFF}}nasıl olduğuna{{CTRL:0000:0003:FDFDFDFF}} bakalım.", "Anlam doğruydu ancak tek satır gereksiz uzundu; kontrol kodları korunarak doğal iki satıra bölündü.", "JP ve diğer resmî diller Glalie’nin durumunu kontrol etmeyi/ona nasıl olduğunu sormayı öneriyor; bilgi değişmedi.")
