#!/usr/bin/env python3
"""In-place Turkish quality/orthography pass for Cave Story 3D SJS files.

- Never edits SJS command tokens.
- Uses the curated word_fixes_v3 dictionary for unambiguous ASCII->Turkish forms.
- Keeps a conservative blacklist for genuinely ambiguous ASCII words.
- Applies hand-reviewed context/line fixes for the remaining known cases.
- Skips credit.sjs; that file is regenerated by credit_sjs_tool.py because it
  contains raw 0xC2 layout bytes.
"""
from pathlib import Path
import re, sys, argparse, collections
sys.path.insert(0, str(Path(__file__).parent))
from word_fixes_v3 import WORD_FIXES

CMD_RE = re.compile(r'<[A-Z0-9+\-]{3}(?:[0-9:+\-]+)?')
WORD_RE = re.compile(r'[A-Za-zÇĞİÖŞÜçğıöşüÂÎÛâîû]+')
TR_LOW = str.maketrans({'İ':'i','I':'ı','Ş':'ş','Ğ':'ğ','Ü':'ü','Ö':'ö','Ç':'ç'})
TR_UP = str.maketrans({'i':'İ','ı':'I','ş':'Ş','ğ':'Ğ','ü':'Ü','ö':'Ö','ç':'Ç'})

def tr_lower(s): return s.translate(TR_LOW).lower()
def tr_upper(s): return s.translate(TR_UP).upper()
def shape_apply(src,dst):
    # Preserve all-caps and title case from the original token.
    if src.isupper(): return tr_upper(dst)
    if len(src)>1 and src[0].isupper() and src[1:].islower():
        return tr_upper(dst[:1])+tr_lower(dst[1:])
    return dst

# These ASCII shapes can map to more than one legitimate Turkish word.
# They are fixed only through explicit context replacements below.
AMBIGUOUS = {
    'su','is','isin','ise','oldun','koyun','aciyor','kir','sus','sinir',
    'bas','basin','basmaya','uca','aci','adin','atti','alir','yazi','koku',
}

# Hand-reviewed phrases/lines. Longer entries first at application time.
PHRASES = {
    'İse yaramaz.':'İşe yaramaz.', 'ise yaramaz.':'işe yaramaz.',
    'İse yaradı.':'İşe yaradı.', 'ise yaradı.':'işe yaradı.',
    'ise yarıyor':'işe yarıyor', 'ise yaramalı':'işe yaramalı',
    'HEP ben toparliyorum!':'HEP ben toparlıyorum!',
    'Sakin aptalca':'Sakın aptalca',
    'yakalanirsan':'yakalanırsan',
    'Sominemden':'Şöminemden', 'Sominedeki':'Şöminedeki',
    'kandiriliyor':'kandırılıyor', 'dovusturmek':'dövüştürmek',
    'Hizlisin!':'Hızlısın!', 'Bir, iki, uç, dört':'Bir, iki, üç, dört',
    'İZİNSİZ GIRISCI TESPİT EDİLDİ!':'İZİNSİZ GİRİŞÇİ TESPİT EDİLDİ!',
    'İZİNSİZ GİRİSÇİ TESPİT EDİLDİ!':'İZİNSİZ GİRİŞÇİ TESPİT EDİLDİ!',
    'O yüzden nobetteyim;':'O yüzden nöbetteyim;',
    'onunmus, dediler.':'onunmuş, dediler.',
    'mıyiz':'mıyız', 'kactiniz':'kaçtınız', 'yanimize':'yanımıza',
    'kacabildin':'kaçabildin', 'hava tankimi':'hava tankımı',
    'Uyuyakaldi.':'Uyuyakaldı.', 'kandiramazsin':'kandıramazsın',
    'iyi adamlardandir.':'iyi adamlardandır.',
    'ilerleyebilecegime':'ilerleyebileceğime',
    'koparirlar':'koparırlar', 'guclendirdim':'güçlendirdim',
    'Korkaklik':'Korkaklık', 'korkaklik':'korkaklık',
    'oynatmasi':'oynatması', 'Sayacta':'Sayaçta', 'sayacta':'sayaçta',
    'kazili':'kazılı',
    'ID Kartı':'Kimlik Kartı',
    'Kazuma: LOL şaka şaka!!!':'Kazuma: Ahaha, şaka şaka!!!',
    'Kazuma: LOL \xfeaka \xfeaka!!!':'Kazuma: Ahaha, şaka şaka!!!',
    'Sanctuary Time Trial Modu':'Kutsal Alan Süre Denemesi',
    'Sanctuary Time Trial':'Kutsal Alan Süre Denemesi',
    'Blast kapısı':'Patlama kapısı', 'Blast Kapısı':'Patlama Kapısı',
    'Up: Yamashita Farm':'Yukarı: Yamashita Çiftliği',
    'Su fıskiyeyi':'Şu fıskiyeyi', 'Su fıskiye':'Şu fıskiye',
    'Su ızgaralar':'Şu ızgaralar', 'Su bacaklarım':'Şu bacaklarım',
    'Su kayayı':'Şu kayayı', 'su kayayı':'şu kayayı',
    'O zaman su\nkayayı':'O zaman şu\nkayayı',
    'SİZ İKİSİ BENİ DİNLİYOR MUSUNUZ':'SİZ İKİNİZ BENİ DİNLİYOR MUSUNUZ',
    'SIZ İKİSİ BENİ DİNLİYOR MUSUNUZ':'SİZ İKİNİZ BENİ DİNLİYOR MUSUNUZ',
    'Biraz daha uca tutamaz mısın?':'Biraz daha ucundan tutamaz mısın?',
    'bir tur yaşam gücü':'bir tür yaşam gücü',
    'Bir tur yaşam gücü':'Bir tür yaşam gücü',
    'Anahtarımı Çalılıklar\'te':'Anahtarımı Çalılıklar\'da',
    'gecmişte':'geçmişte', 'mıydi':'mıydı', 'bir tur':'bir tür',
    'korkaktir':'korkaktır', 'ziplayabilirsen':'zıplayabilirsen',
    'Içeride':'İçeride', 'Içeri ':'İçeri ', 'İse yaradı':'İşe yaradı',
    'bas belası':'baş belası', 'Işkenceden':'İşkenceden',
    "Çalılıklar'e":"Çalılıklar'a",
    'Sakız bazasi mi dedin?':'Sakız bazı mı dedin?',
}

# Additional safe mappings that were found after the original dictionary grew.
EXTRA_WORDS = {
    'toparliyorum':'toparlıyorum','yakalanirsan':'yakalanırsan',
    'sominemden':'şöminemden','sominedeki':'şöminedeki',
    'kandiriliyor':'kandırılıyor','dovusturmek':'dövüştürmek',
    'hizlisin':'hızlısın','nobetteyim':'nöbetteyim','onunmus':'onunmuş',
    'kactiniz':'kaçtınız','yanimize':'yanımıza','kacabildin':'kaçabildin',
    'tankimi':'tankımı','uyuyakaldi':'uyuyakaldı','kandiramazsin':'kandıramazsın',
    'adamlardandir':'adamlardandır','ilerleyebilecegime':'ilerleyebileceğime',
    'koparirlar':'koparırlar','guclendirdim':'güçlendirdim','korkaklik':'korkaklık',
    'oynatmasi':'oynatması','sayacta':'sayaçta','kazili':'kazılı',
    'kullanirsan':'kullanırsan','anlamiyorsun':'anlamıyorsun',
}
SAFE_FIXES = dict(WORD_FIXES)
SAFE_FIXES.update(EXTRA_WORDS)

# no-op entries are harmless but skipped for cleaner reporting.
for k in list(SAFE_FIXES):
    if k in AMBIGUOUS or SAFE_FIXES[k] == k:
        SAFE_FIXES.pop(k, None)


def fix_segment(seg, counter):
    # Hand-reviewed phrase replacements first, longest to shortest.
    for a,b in sorted(PHRASES.items(), key=lambda kv: len(kv[0]), reverse=True):
        n=seg.count(a)
        if n:
            seg=seg.replace(a,b); counter['phrase:'+a]+=n
    def rw(m):
        w=m.group(0)
        k=tr_lower(w)
        # Dictionary keys were curated against ASCII spellings.
        k_ascii=(k.replace('ç','c').replace('ğ','g').replace('ı','i')
                   .replace('ö','o').replace('ş','s').replace('ü','u'))
        target=SAFE_FIXES.get(k_ascii)
        if not target: return w
        out=shape_apply(w,target)
        if out!=w: counter['word:'+k_ascii]+=1
        return out
    seg=WORD_RE.sub(rw,seg)
    # Some context fixes become matchable after word fixes.
    for a,b in sorted(PHRASES.items(), key=lambda kv: len(kv[0]), reverse=True):
        n=seg.count(a)
        if n:
            seg=seg.replace(a,b); counter['phrase2:'+a]+=n
    return seg


def process_file(path,counter):
    raw=path.read_bytes(); text=raw.decode('cp1254','surrogateescape')
    out=[]; pos=0
    for m in CMD_RE.finditer(text):
        out.append(fix_segment(text[pos:m.start()],counter)); out.append(m.group(0)); pos=m.end()
    out.append(fix_segment(text[pos:],counter))
    new=''.join(out)
    if new!=text:
        path.write_bytes(new.encode('cp1254','surrogateescape'))
        return True
    return False


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('root', nargs='?', default='/mnt/data/cs3d_work/final/000400000004D200/romfs/data')
    ap.add_argument('--report', default='/mnt/data/cs3d_work/quality_v4_report.txt')
    a=ap.parse_args(); root=Path(a.root)
    counter=collections.Counter(); changed=[]
    for p in sorted(root.rglob('*.sjs')):
        if p.name.lower()=='credit.sjs': continue
        if process_file(p,counter): changed.append(p.relative_to(root).as_posix())
    lines=[
        'Cave Story 3D TR - V4 kalite geçişi',
        f'Değişen SJS dosyası: {len(changed)}',
        f'Toplam düzeltme: {sum(counter.values())}', '',
        'Değişen dosyalar:', *changed, '', 'Düzeltme sayımları:'
    ]
    lines += [f'{k}\t{v}' for k,v in counter.most_common()]
    Path(a.report).write_text('\n'.join(lines)+'\n',encoding='utf-8')
    print(f'changed scripts: {len(changed)}; replacements: {sum(counter.values())}')

if __name__=='__main__': main()
