# -*- coding: utf-8 -*-
SBVOICE={
'It’s Bravely Second!':'İşte Bravely Second!',
'Yeaaah, I stopped the clock.':'Eveeet, zamanı durdurdum.',
'Just TRY to hold me back!':'Hadi, beni durdurmayı dene!',
'We get SP when the system sleeps, right?':'Sistem uyurken SP kazanıyoruz, değil mi?',
'What? Sleep Mode isn’t the only way to get SP!?':'Ne? SP kazanmanın tek yolu Uyku Modu değil mi!?',
'Now I’m MAD!':'Şimdi gerçekten kızdım!',
'You’re not getting off the hook!':'Bu kez elimden kurtulamazsın!',
'Apologize, and I might let you go.':'Özür dile, belki seni bırakırım.',
'Too late for apologies!':'Özür dilemek için çok geç!',
'Ugh, no one likes a guy who can’t take a hint!':'Off, laf anlamayan erkeklerden kimse hoşlanmaz!',
'Now, then. Shall we begin?':'Pekâlâ. Başlayalım mı?',
'If you hope to run, I’d get on that.':'Kaçmayı düşünüyorsan acele et.',
'Of course, if you ran, I’d chase you down!':'Tabii kaçarsan peşinden gelirim!',
'I’m finally getting warmed up!':'Sonunda ısınmaya başladım!',
'I’m a lot meaner than I look.':'Göründüğümden çok daha acımasızım.',
'Are you black, or white? Let’s find out.':'Siyah mısın, beyaz mı? Görelim bakalım.',
'You’ll be black and white and red all over.':'Birazdan siyah, beyaz ve kıpkırmızı olacaksın.',
'Get ready for a doozy!':'Sıkı dur, şimdi asıl darbeyi göreceksin!',
'You’ll get the works, with a cherry on top!':'Her şeyi üstüne bir de bonusuyla alacaksın!',
'I’m impressed you got me this mad!':'Beni bu kadar kızdırmayı başarmana şaşırdım!',
'Here’s some proverbs for you!':'Sana birkaç atasözü söyleyeyim!',
'The early bird gets Tiz!':'Erken kalkan Tiz’i kapar!',
'Fight fire with Tiz!':'Ateşe Tiz’le karşılık ver!',
'Once bitten, twice Tiz!':'Bir ısırılan, iki kere Tiz der!',
'If you can’t beat ’em, join Agnès…hee hee!':'Yenemiyorsan Agnès’e katıl… hihihi!',
'Heh, feel any smarter?':'Heh, şimdi daha akıllı hissediyor musun?',
'Cause I guarantee this is gonna smart!':'Çünkü bunun fena can yakacağı kesin!',
'All this exercise has me hungry!':'Bunca hareket beni acıktırdı!',
'You look like a nice snack!':'Sen güzel bir atıştırmalığa benziyorsun!',
'WHAT!? Ringabel, this is hardly the time!':'NE!? Ringabel, şimdi hiç sırası değil!',
}
EXACT={
'You are isolated from the world!':'Dünyadan yalıtıldın!',
'Centro Keep Ruins':'Centro Kalesi Harabeleri',
'Yulyana Woods':'Yulyana Ormanı',
'Dimension’s Hasp':'Boyut Kıskacı',
'Underflow – 3F':'Alt Akıntı – 3F',
}
