# -*- coding: utf-8 -*-
"""Deep audit translations for English/legacy strings still present in Common_en/MessageTable.
Exact-match only; placeholders/control markup are preserved. Existing user-translated cells are never overwritten.
"""
MESSAGE_DEEP = {
# MenuMessageData
'Warning! All other abilities will\nbe removed when this is equipped.\nDo you want to continue?':'Uyarı! Bu kuşanıldığında diğer tüm\nyetenekler kaldırılacak.\nDevam etmek istiyor musun?',
'Add friends to use the\nAbilink feature.\nTry adding some friends!':'Yetenek Bağı özelliğini kullanmak için\narkadaş ekle.\nBirkaç arkadaş eklemeyi dene!',
'%ls is already abilinked\nwith %ls.':'%ls zaten %ls ile\nYetenek Bağı kurmuş.',
'The following support abilities will be\nremoved if you change the abilink.':'Yetenek Bağı değişirse aşağıdaki\ndestek yetenekleri kaldırılacak.',
'Show and use recovery items.':'İyileştirme eşyalarını göster ve kullan.',
'Show new items.':'Yeni eşyaları göster.',
'Show attack items.':'Saldırı eşyalarını göster.',
'Show compounding items.':'Karışım eşyalarını göster.',
'Show key items.':'Önemli eşyaları göster.',
'Show weapons.':'Silahları göster.',
'Show shields, armor, and accessories.':'Kalkan, zırh ve aksesuarları göster.',
'Show outfits that change appearance.':'Görünüşü değiştiren kıyafetleri göster.',
'There are no items.':'Hiç eşya yok.',
'%ls increased by %d!':'%ls %d arttı!',
'Cannot be used now.':'Şu anda kullanılamaz.',
'Use white magic.':'Beyaz Büyü kullan.',
'Use black magic.':'Kara Büyü kullan.',
'Use time magic.':'Zaman Büyüsü kullan.',
'Use sword magic.':'Kılıç Büyüsü kullan.',
'Use summoning magic.':'Çağırma Büyüsü kullan.',
'You have no commands for using magic.':'Büyü kullanabileceğin bir komut yok.',
'You haven’t learned any magic.':'Henüz hiç büyü öğrenmedin.',
'Equip head armor.':'Baş zırhı kuşan.',
'Equip torso armor.':'Gövde zırhı kuşan.',
'Equip accessories.':'Aksesuar kuşan.',
'Equip outfits that change appearance.':'Görünüşü değiştiren kıyafet kuşan.',
'Select all recommended equipment from your inventory.':'Envanterindeki önerilen tüm teçhizatı seç.',
'Select a weapon.':'Bir silah seç.',
'Select a newly acquired weapon.':'Yeni edinilen bir silah seç.',
'Select an outfit that changes appearance.':'Görünüşü değiştiren bir kıyafet seç.',
'Select a weapon and shield.':'Bir silah ve kalkan seç.',
'Select a newly acquired weapon or shield.':'Yeni edinilen bir silah veya kalkan seç.',
'Select head armor.':'Baş zırhı seç.',
'Select newly acquired head armor.':'Yeni edinilen baş zırhını seç.',
'Select a hat.':'Bir şapka seç.',
'Select a helm.':'Bir miğfer seç.',
'Select torso armor.':'Gövde zırhı seç.',
'Select newly acquired torso armor.':'Yeni edinilen gövde zırhını seç.',
'Select a piece of light armor.':'Bir hafif zırh seç.',
'Select a piece of heavy armor.':'Bir ağır zırh seç.',
'Select an accessory.':'Bir aksesuar seç.',
'Select a newly acquired accessory.':'Yeni edinilen bir aksesuar seç.',
'Select a newly acquired outfit that changes appearance.':'Yeni edinilen, görünüşü değiştiren bir kıyafet seç.',
'Remove the equipped item.':'Kuşanılmış eşyayı çıkar.',
'Select recommended equipment from your inventory.':'Envanterinden önerilen teçhizatı seç.',
'Empty':'Boş',
'Recommended':'Önerilen',
'Equipping a two-handed weapon.':'İki elli silah kuşanılıyor.',
'Switching left hand\nequipment to right hand.':'Sol el teçhizatı\nsağ ele geçiriliyor.',
'Switching right hand\nequipment to left hand.':'Sağ el teçhizatı\nsol ele geçiriliyor.',
'Switching weapon to right hand.':'Silah sağ ele geçiriliyor.',
'AllRec':'Tüm Önr.',
'2-Hand':'2 El',
'R Hand':'Sağ El',
'L Hand':'Sol El',
'Physical attack power for both hands.':'İki elin fiziksel saldırı gücü.',
'Physical attack power for the right hand.':'Sağ elin fiziksel saldırı gücü.',
'Physical attack power for the left hand.':'Sol elin fiziksel saldırı gücü.',
'Defense against physical attacks.':'Fiziksel saldırılara karşı savunma.',
'Magic attack power.':'Büyü saldırı gücü.',
'Defense against magic attacks.':'Büyü saldırılarına karşı savunma.',
'Ability to hit with physical attacks.':'Fiziksel saldırıların isabet yeteneği.',
'Ability to evade physical attacks.\nAlso affects enemy attack hit count.':'Fiziksel saldırılardan kaçınma yeteneği.\nDüşman saldırılarının isabet sayısını da etkiler.',
'Maximum HP.':'Azami HP.',
'Maximum MP.':'Azami MP.',
'Affects physical attack power.':'Fiziksel saldırı gücünü etkiler.',
'Affects physical defense ability.':'Fiziksel savunmayı etkiler.',
'Affects magic attack power and\nchance to inflict status ailments.':'Büyü saldırı gücünü ve durum\netkisi verme ihtimalini etkiler.',
'Affects magic defense, healing power,\nand chance to avoid status ailments.':'Büyü savunmasını, iyileştirme gücünü ve\ndurum etkilerinden kaçınma ihtimalini etkiler.',
'Affects physical attack accuracy and\nBrave Attack rate.':'Fiziksel saldırı isabetini ve\nBrave Saldırısı oranını etkiler.',
'Affects physical attack evasion, hit\ncount, speed, and first strike rate.':'Fiziksel kaçınmayı, isabet sayısını,\nhızı ve ilk saldırı oranını etkiler.',
'Reduces damage from the specified\nelement.':'Belirtilen elementten alınan\nhasarı azaltır.',
'Nullifies damage from the specified\nelement.':'Belirtilen elementten alınan\nhasarı geçersiz kılar.',
'Deals minor damage each combat turn,\nor after traveling a certain distance.':'Her savaş turunda veya belirli bir\nmesafe yürüdükçe az miktarda hasar verir.',
'Greatly reduces physical attack\naccuracy. Cannot evade physical attacks.':'Fiziksel saldırı isabetini büyük ölçüde\nazaltır. Fiziksel saldırılardan kaçınılamaz.',
'Unable to use abilities such as magic\nthat require you to speak.':'Konuşmayı gerektiren büyü gibi\nyetenekler kullanılamaz.',
'Unable to act or evade physical attacks.\nRemoved when hit by a physical attack.':'Hareket edilemez veya fiziksel saldırılardan\nkaçınılamaz. Fiziksel darbe alınca kalkar.',
'Unable to act or evade physical attacks.':'Hareket edilemez veya fiziksel saldırılardan kaçınılamaz.',
'Unable to use Brave or Default, and\nBP of 1 or more is reduced to 0.':'Brave veya Default kullanılamaz;\n1 veya üzerindeki BP 0’a düşer.',
'Performs random actions against\na random target.':'Rastgele bir hedefe karşı\nrastgele eylemler yapar.',
'Acts as if allied with the enemy.':'Düşmanın müttefikiymiş gibi davranır.',
'Knocked out regardless of HP remaining.':'Kalan HP’den bağımsız olarak savaş dışı kalır.',
'Unable to act or evade physical\nattacks. Can be removed with dispel.':'Hareket edilemez veya fiziksel saldırılardan\nkaçınılamaz. Dispel ile kaldırılabilir.',
'Show on Top':'Üstte Göster',
'Show on Bottom':'Altta Göster',
'You have no special moves.':'Hiç özel hamlen yok.',
'Select a sword special move.':'Bir kılıç özel hamlesi seç.',
'Select an axe special move.':'Bir balta özel hamlesi seç.',
'Select a spear special move.':'Bir mızrak özel hamlesi seç.',
'Select a rod special move.':'Bir değnek özel hamlesi seç.',
'Select a staff special move.':'Bir asa özel hamlesi seç.',
'Select a dagger special move.':'Bir hançer özel hamlesi seç.',
'Select a bow special move.':'Bir yay özel hamlesi seç.',
'Select a katana special move.':'Bir katana özel hamlesi seç.',
'Select a knuckles/unarmed special move.':'Bir muşta/silahsız özel hamlesi seç.',
'Select a part that adds elemental damage.':'Element hasarı ekleyen bir parça seç.',
'Select a part that adds power.':'Güç ekleyen bir parça seç.',
'Select a part that adds damage to a certain enemy family.':'Belirli bir düşman türüne ek hasar veren bir parça seç.',
'Select a part that inflicts a status ailment.':'Durum etkisi uygulayan bir parça seç.',
'Select a part the increases HP recovered.':'İyileştirilen HP miktarını artıran bir parça seç.',
'Select a part that cures status ailments.':'Durum etkilerini iyileştiren bir parça seç.',
'Select a part that increases MP recovered.':'Geri kazanılan MP miktarını artıran bir parça seç.',
'Select a part that increases BP.':'BP artıran bir parça seç.',
'Select a part that adds turns.':'Tur ekleyen bir parça seç.',
'Select a part that boosts stats.':'Statları yükselten bir parça seç.',
'Select a part granting resistance to status ailments.':'Durum etkilerine direnç kazandıran bir parça seç.',
'Select a part that boosts elemental resistance.':'Element direncini artıran bir parça seç.',
'Select a part that reduces stats.':'Statları düşüren bir parça seç.',
'Select a part that reduces status ailment resistance.':'Durum etkisi direncini azaltan bir parça seç.',
'Select a part that weakens elemental resistance.':'Element direncini zayıflatan bir parça seç.',
'Remove a special move part.':'Özel hamle parçasını kaldır.',
'The data you enter may be seen by others.\nDo not enter any personal information.':'Girdiğin veriler başkaları tarafından görülebilir.\nKişisel bilgi girme.',
'This is how fast messages will appear.':'Mesajların görüntülenme hızını belirler.',
'Return to Config without resetting.':'Sıfırlamadan Ayarlar’a dön.',
'Adjust battle settings.':'Savaş ayarlarını düzenle.',
'Adjust sound settings.':'Ses ayarlarını düzenle.',
'Adjust message settings.':'Mesaj ayarlarını düzenle.',
'Adjust game settings.':'Oyun ayarlarını düzenle.',
'Set the difficulty.':'Zorluğu ayarla.',
'Return to %ls settings without resetting.':'Sıfırlamadan %ls ayarlarına dön.',
'Set whether to confirm at turn start.':'Tur başında onay istenip istenmeyeceğini ayarla.',
'Set the button assignments.':'Düğme atamalarını ayarla.',
'Confirm when starting a turn.':'Tur başlarken onay iste.',
'Do not confirm at turn start. (Cannot change commands.)':'Tur başında onay isteme. (Komutlar değiştirilemez.)',
'Set the Brave and Default button assignments.':'Brave ve Default düğme atamalarını ayarla.',
'Select a language for voices in the game.':'Oyundaki seslendirme dilini seç.',
'Select a language for text in the game.':'Oyundaki metin dilini seç.',
'Select how to view messages during events.':'Olaylarda mesajların nasıl gösterileceğini seç.',
'In-game voices set to %ls.':'Oyun içi seslendirme: %ls.',
'In-game text set to %ls.':'Oyun içi metin: %ls.',
'Messages will appear at this speed.':'Mesajlar bu hızda görüntülenir.',
'Press the confirm button to see the next message.':'Sonraki mesaj için onay düğmesine bas.',
'Messages are displayed in sync with voices.':'Mesajlar seslendirmeyle eşzamanlı gösterilir.',
'Set the controls using +Control Pad left/right.':'+Kontrol Pedi sol/sağ ile kontrolleri ayarla.',
'Set whether to use the autosave feature.':'Otomatik kayıt kullanılıp kullanılmayacağını ayarla.',
'Confirm/cancel with +Control Pad left/right.':'+Kontrol Pedi sol/sağ ile onayla/iptal et.',
'Do not confirm/cancel with +Control Pad left/right.':'+Kontrol Pedi sol/sağ ile onaylama/iptal etme.',
'Overwrite save data automatically when switching maps, etc.':'Harita değiştirirken vb. kayıt verisinin üzerine otomatik yaz.',
'Do not use the autosave feature.':'Otomatik kayıt özelliğini kullanma.',
'Set whether to display destination markers.':'Hedef işaretlerinin gösterilip gösterilmeyeceğini ayarla.',
'Set whether to acquire EXP after battle.':'Savaş sonrası EXP kazanımını ayarla.',
'Set whether to acquire money after battle.':'Savaş sonrası para kazanımını ayarla.',
'Set whether to acquire job points after battle.':'Savaş sonrası JP kazanımını ayarla.',
'Set the strength of enemies.':'Düşmanların gücünü ayarla.',
'Set the enemy encounter rate when traveling.':'Yolculukta düşmanla karşılaşma oranını ayarla.',
'Show destination markers.':'Hedef işaretlerini göster.',
'Do not show destination markers.':'Hedef işaretlerini gösterme.',
'Acquire EXP.':'EXP kazan.',
'Do not acquire EXP.':'EXP kazanma.',
'Acquire money.':'Para kazan.',
'Do not acquire money.':'Para kazanma.',
'Acquire job points.':'JP kazan.',
'Do not acquire job points.':'JP kazanma.',
'Press up/down to set the encounter rate.':'Karşılaşma oranını ayarlamak için yukarı/aşağı bas.',
'The encounter rate has been\nset to a low value. Note that\nthis will make it harder to\ngain levels.':'Karşılaşma oranı düşük bir\ndeğere ayarlandı. Bunun seviye\natlamayı zorlaştıracağını unutma.',
'You will no longer encounter\nenemies while moving. Note\nthat this will make it harder to\ngain levels.\n':'Hareket ederken artık düşmanla\nkarşılaşmayacaksın. Bunun seviye\natlamayı zorlaştıracağını unutma.\n',
'Enemies are weaker.':'Düşmanlar daha zayıf.',
'Standard difficulty.':'Standart zorluk.',
'Enemies are stronger.':'Düşmanlar daha güçlü.',
'Confirm at turn start':'Tur Başında Onayla',
'Update data upon Send':'Gönderimde Veriyi Güncelle',
'EXP Acquired':'Kazanılan EXP',
'pg Acquired':'Kazanılan pg',
'JP Acquired':'Kazanılan JP',
'Battle':'Savaş',
'Sound':'Ses',
'Messages':'Mesajlar',
'Game':'Oyun',
'The language settings have been changed.\nDo you want to use these settings?\n\nVoice: 【%ls】\nText: 【%ls】':'Dil ayarları değiştirildi.\nBu ayarlar kullanılsın mı?\n\nSes: 【%ls】\nMetin: 【%ls】',
'Change character name(s) to the\ndefault name(s) for %ls?':'Karakter adları %ls için\nvarsayılan adlara döndürülsün mü?',
'Are you certain?\n* Autosave settings will not be changed.':'Emin misin?\n* Otomatik kayıt ayarları değişmeyecek.',
# TomodachiMessageData
'Communications were\ninterrupted.':'İletişim kesildi.',
'No friends to update.':'Güncellenecek arkadaş yok.',
'Delete this data?':'Bu veri silinsin mi?',
'Data deleted.':'Veri silindi.',
'The data is protected and\ncannot be deleted.':'Veri korumalı olduğundan\nsilinemez.',
"You have too many friends!\nOnce you reach 20 friends,\nyou'll have to delete some\nto add more.":'Çok fazla arkadaşın var!\n20 arkadaşa ulaştığında yenilerini\neklemek için bazılarını silmelisin.',
'This friend is Abilinked\nwith %ls.\nDelete this data?':'Bu arkadaş %ls ile\nYetenek Bağı kurmuş.\nVeri silinsin mi?',
'Data updated.':'Veri güncellendi.',
'You became friends\nwith %ls.':'%ls ile arkadaş oldun.',
'You have made %d friend(s).':'%d arkadaş edindin.',
'There were no friends registered on\nthe system that could be added.':'Sistemde eklenebilecek kayıtlı\narkadaş bulunamadı.',
'Data for %d people updated.':'%d kişinin verisi güncellendi.',
'You sent %d Net Friend Invite(s).':'%d Ağ Arkadaşı daveti gönderdin.',
'You encountered %d other(s) with StreetPass.':'StreetPass ile %d kişiyle karşılaştın.',
'You are already friends\nwith %ls.':'%ls ile zaten arkadaşsın.',
'Waiting for client unit...':'İstemci birim bekleniyor...',
'Waiting for response from host unit...':'Ana birimden yanıt bekleniyor...',
'Adding friend...':'Arkadaş ekleniyor...',
'Updating data...':'Veri güncelleniyor...',
'Updating StreetPass data...':'StreetPass verisi güncelleniyor...',
'Closing the Nintendo 3DS system\nor opening the HOME Menu may\ninterrupt the connection.':'Nintendo 3DS sistemini kapatmak\nveya HOME Menüsünü açmak\nbağlantıyı kesebilir.',
'Registering StreetPass data...':'StreetPass verisi kaydediliyor...',
'Searching for host unit...':'Ana birim aranıyor...',
'Do not turn the system off during communications.':'İletişim sırasında sistemi kapatma.',
'To use this feature, you must accept\nthe terms of the Nintendo 3DS\nService User Agreement.\nIn System Settings, select Internet\nSettings > Other Information >\nUser Agreement and agree to the terms.':'Bu özelliği kullanmak için Nintendo 3DS\nHizmet Kullanıcı Sözleşmesi’ni kabul etmelisin.\nSistem Ayarları > İnternet Ayarları >\nDiğer Bilgiler > Kullanıcı Sözleşmesi’nden\nkoşulları kabul et.',
'Cannot communicate because\n"Online Interaction" is\nrestricted under Parental\nControls.':'Ebeveyn Kontrollerinde\n“Çevrimiçi Etkileşim” kısıtlandığı\niçin iletişim kurulamıyor.',
'Using Internet communication and\nStreetPass may result in information\nbeing sent to third parties. Keep\nthis in mind when adding comments.':'İnternet iletişimi ve StreetPass kullanımı\nbilgilerin üçüncü taraflara gönderilmesine\nyol açabilir. Yorum eklerken bunu göz önünde bulundur.',
'Registering friend...':'Arkadaş kaydediliyor...',
'You registered %ls\nas a friend.':'%ls arkadaş olarak\nkaydedildi.',
'Data protected.':'Veri korumaya alındı.',
'Data no longer protected.':'Veri koruması kaldırıldı.',
'You can only protect up to\nfive guests.':'En fazla beş misafirin\nverisini koruyabilirsin.',
'The data you enter may be seen by\nothers. Do not enter any personal\ninformation.':'Girdiğin veriler başkaları tarafından\ngörülebilir. Kişisel bilgi girme.',
'Send complete.\nUpload via Internet communication?':'Gönderim tamamlandı.\nİnternet üzerinden yüklensin mi?',
'Do not turn the system off during registration.':'Kayıt sırasında sistemi kapatma.',
'Do not turn the system off during update.':'Güncelleme sırasında sistemi kapatma.',
'StreetPass registration may\nbe interrupted if you turn\nthe system power off while\nregistering.':'Kayıt sırasında sistemi kapatırsan\nStreetPass kaydı kesilebilir.',
'The update of StreetPass\ndata may be interrupted if\nyou turn the system power\noff while updating.':'Güncelleme sırasında sistemi kapatırsan\nStreetPass veri güncellemesi kesilebilir.',
'To use this feature, you must accept\nthe terms of the Nintendo 3DS\nService User Agreement. In System\nSettings, select Internet Settings >\nOther Information > User Agreement\nand agree to the terms.':'Bu özelliği kullanmak için Nintendo 3DS\nHizmet Kullanıcı Sözleşmesi’ni kabul etmelisin.\nSistem Ayarları > İnternet Ayarları > Diğer Bilgiler >\nKullanıcı Sözleşmesi’nden koşulları kabul et.',
'Internet Settings can be found\nunder the System Settings.':'İnternet Ayarları, Sistem Ayarları\niçinde bulunur.',
'To communicate over the Internet,\nturn wireless communication on by\npushing the wireless switch.':'İnternet üzerinden iletişim için\nkablosuz anahtarını açarak\nkablosuz iletişimi etkinleştir.',
'Profile information uploaded.':'Profil bilgileri yüklendi.',
'You have already sent a Net Friend\nInvite today. Try again tomorrow.':'Bugün zaten bir Ağ Arkadaşı\ndaveti gönderdin. Yarın tekrar dene.',
'Local wireless cannot be used\nbecause of parental control\nrestrictions.':'Ebeveyn kontrolü kısıtlamaları nedeniyle\nyerel kablosuz kullanılamıyor.',
'To use local wireless, turn wireless\ncommunication on by pushing the\nwireless switch.':'Yerel kablosuzu kullanmak için\nkablosuz anahtarını aç.',
'Add friends using local\nwireless.':'Yerel kablosuz ile\narkadaş ekle.',
'Select a user to act as the host unit.':'Ana birim olacak kullanıcıyı seç.',
'Add %ls as a friend and\nadd them as a friend on your system?':'%ls hem oyunda hem de sistemde\narkadaş olarak eklensin mi?',
'Register Bravely Default StreetPass\ndata to the system?':'Bravely Default StreetPass verisi\nsisteme kaydedilsin mi?',
'StreetPass data registered.\nStreetPass will work automatically\neven when not playing this game.':'StreetPass verisi kaydedildi.\nBu oyunu oynamıyorken bile\nStreetPass otomatik çalışacak.',
'You cannot register any more\nStreetPass data to the system.\nCancel StreetPass for other software\nusing StreetPass Management under\nSystem Settings.':'Sisteme daha fazla StreetPass verisi\nkaydedemezsin. Sistem Ayarları altındaki\nStreetPass Yönetiminden başka yazılımların\nStreetPass kaydını iptal et.',
'StreetPass unavailable because\n"StreetPass" is restricted under\nParental Controls.':'Ebeveyn Kontrollerinde “StreetPass”\nkısıtlandığı için StreetPass kullanılamıyor.',
'StreetPass data is corrupted.\nDelete the StreetPass data for\nBravely Default using StreetPass\nManagement under System Settings.':'StreetPass verisi bozuk. Sistem Ayarları\naltındaki StreetPass Yönetiminden\nBravely Default StreetPass verisini sil.',
'To update StreetPass data,\ntouch the Inbox icon on the\nmap menu.':'StreetPass verisini güncellemek için\nharita menüsündeki Gelen Kutusu\nsimgesine dokun.',
'StreetPass data updated.':'StreetPass verisi güncellendi.',
'You did not pass by anybody.':'Kimseyle karşılaşmadın.',
'No host unit found.':'Ana birim bulunamadı.',
'Showing data received via Internet communication.':'İnternet üzerinden alınan veriler gösteriliyor.',
'Showing data received via local wireless.':'Yerel kablosuzdan alınan veriler gösteriliyor.',
'Showing data received via StreetPass.':'StreetPass ile alınan veriler gösteriliyor.',
'Add a friend using Internet communication.':'İnternet üzerinden arkadaş ekle.',
'Add a friend using local wireless.':'Yerel kablosuz ile arkadaş ekle.',
'Update data using Internet communication.':'Veriyi İnternet üzerinden güncelle.',
'Update data using local wireless.':'Veriyi yerel kablosuz ile güncelle.',
'Select a friend to stop updating data for.':'Veri güncellemesi durdurulacak arkadaşı seç.',
'You are now friends\nwith %ls.\nUpdated data\nfor %ls.':'Artık %ls ile arkadaşsın.\n%ls için veri güncellendi.',
'You are now friends\nwith %ls.\nYou have made %d friend(s).':'Artık %ls ile arkadaşsın.\nToplam %d arkadaş edindin.',
'You have made %d friend(s).\nUpdated data for %ls.':'%d arkadaş edindin.\n%ls verisi güncellendi.',
'You have made %d friend(s).\nUpdated data for %d friend(s).':'%d arkadaş edindin.\n%d arkadaşın verisi güncellendi.',
'Saving data.\nDo not turn off the system or\nremove the card.':'Veri kaydediliyor.\nSistemi kapatma veya\nkartı çıkarma.',
'Failed to save data.\nReturn to the title screen and\ndelete the data.':'Veri kaydedilemedi.\nBaşlık ekranına dönüp\nveriyi sil.',
'Cannot connect to the network.\nPerform a System Transfer for the\nNintendo 3DS or contact the Support\nCenter.':'Ağa bağlanılamıyor. Nintendo 3DS için\nSistem Aktarımı yap veya Destek Merkeziyle\niletişime geç.',
'An error has occurred.\nPlease try connecting again later.':'Bir hata oluştu.\nDaha sonra tekrar bağlanmayı dene.',
'To prevent data updates after using\nSend in battle, set "Update data\nupon Send" to "No" under Tactics >\nConfig on the menu screen.':'Savaşta Gönder kullandıktan sonra veri\ngüncellenmesini önlemek için menüde\nTaktikler > Ayarlar > “Gönderimde Veriyi Güncelle”\nseçeneğini “Hayır” yap.',

# TitleMessageData
'We’d like to give you a gift\nfor playing the demo version!\n\nWill you accept it?':'Demo sürümünü oynadığın için\nsana bir hediye vermek istiyoruz!\n\nKabul edecek misin?',
'%ls received!':'%ls alındı!',
'%d villager(s) have come to help rebuild\nNorende Village!':'Norende Köyü’nü yeniden kurmaya yardım etmek için\n%d köylü geldi!',
'Friend information transferred!':'Arkadaş bilgileri aktarıldı!',
'We hope you enjoy the gift,\nand now, of course, the game itself!':'Hediyenin ve elbette\noyunun tadını çıkar!',
'Demo version save data not found. Please check\nto see if save data has been created correctly.':'Demo sürümüne ait kayıt verisi bulunamadı.\nKayıt verisinin doğru oluşturulduğunu kontrol et.',
'Demo version save data not recognized.':'Demo sürümü kayıt verisi tanınamadı.',
'Caldislan Recovery Set':'Caldisla İyileştirme Seti',
'Caldislan White Mage’s Set':'Caldisla Beyaz Büyücü Seti',
'Caldislan Black Mage’s Set':'Caldisla Kara Büyücü Seti',
'Caldislan Soldier’s Set':'Caldisla Asker Seti',
'Caldislan Knight’s Set':'Caldisla Şövalye Seti',
'Caldislan Adventurer’s Set':'Caldisla Maceracı Seti',
'Caldislan Relief Set':'Caldisla Yardım Seti',
'<R>Save data already exists.</>\nDo you want to copy anyway?':'<R>Kayıt verisi zaten var.</>\nYine de kopyalansın mı?',
'Copying data.\nDo not turn off the system or\nremove the card.':'Veri kopyalanıyor.\nSistemi kapatma veya\nkartı çıkarma.',
'Data copied.\nReturning to the title screen.':'Veri kopyalandı.\nBaşlık ekranına dönülüyor.',
'Failed to copy data.\nReturning to the title screen.':'Veri kopyalanamadı.\nBaşlık ekranına dönülüyor.',
'Saving extra data to SD Card.\nThis data will be used with upcoming\ngames in the series, and cannot be\nused with this game.':'Ek veri SD Karta kaydediliyor.\nBu veri serinin gelecek oyunlarında kullanılacak\nve bu oyunda kullanılamaz.',
'Save extra data to the SD Card?':'Ek veri SD Karta kaydedilsin mi?',
'Copying data to SD Card.\nDo not turn off the system or\nremove the card.':'Veri SD Karta kopyalanıyor.\nSistemi kapatma veya\nkartı çıkarma.',
'Not enough free space on the SD Card.\nAt least %d KB of free space are\nrequired to save extra data.':'SD Kartta yeterli boş alan yok.\nEk veriyi kaydetmek için en az\n%d KB boş alan gerekli.',
'The extra data on the SD Card is\ncorrupted. Re-save it now?':'SD Karttaki ek veri bozuk.\nŞimdi yeniden kaydedilsin mi?',
'There is no extra data.\nDo you want to create extra data?':'Ek veri yok.\nEk veri oluşturulsun mu?',
'There is other extra data.\nIt will all be deleted to create\na new save. Continue?':'Başka ek veriler var. Yeni kayıt oluşturmak\niçin hepsi silinecek. Devam edilsin mi?',
'Are you sure you want to delete\nsave and related system data\nand reset to default values?\n(SP and SP Drinks will be lost as well.)':'Kayıt ve ilgili sistem verilerini silip\nvarsayılan değerlere dönmek istediğinden emin misin?\n(SP ve SP İçecekleri de kaybolacak.)',
'Are you sure you want to\ndelete this save data?':'Bu kayıt verisini silmek\nistediğinden emin misin?',
'Data deleted.\nReturning to the title screen.':'Veri silindi.\nBaşlık ekranına dönülüyor.',
'Failed to delete data.\nReturning to the title screen.':'Veri silinemedi.\nBaşlık ekranına dönülüyor.',
'Enemies are weaker.\nChoose this if you want to focus\non enjoying the story. You can\nchange the settings in-game from\nthe Config screen as well.':'Düşmanlar daha zayıftır.\nHikâyeye odaklanmak istiyorsan bunu seç.\nBu ayarı oyun içinde Ayarlar ekranından\nda değiştirebilirsin.',
'Standard difficulty.\nRecommended for all but the most\nhardcore players! You can change\nthe settings in-game from the\nConfig screen as well.':'Standart zorluk.\nEn sıkı oyuncular dışında herkese önerilir!\nBu ayarı oyun içinde Ayarlar ekranından\nda değiştirebilirsin.',
'Enemies are stronger.\nFor those who need an extra\nchallenge. You can change the\nsettings in-game from the Config\nscreen as well.':'Düşmanlar daha güçlüdür.\nDaha zorlu bir mücadele isteyenler için.\nBu ayarı oyun içinde Ayarlar ekranından\nda değiştirebilirsin.',
'Save data will be overwritten\nautomatically when you enter or\nexit cities and dungeons, when\nyou move between dungeon\nfloors, etc. This option is\nrecommended to avoid losing\nyour progress.\n*You can change the settings from\nthe Config screen after starting.':'Şehirlere veya zindanlara girip çıkarken,\nzindan katları arasında geçerken vb.\nkayıt verisinin üzerine otomatik yazılır.\nİlerlemeni kaybetmemek için önerilir.\n*Oyuna başladıktan sonra Ayarlar ekranından\ndeğiştirebilirsin.',
'You will need to save manually.\n\nYou can change the settings from\nthe Config screen after starting.':'Elle kayıt yapman gerekir.\n\nOyuna başladıktan sonra bu ayarı\nAyarlar ekranından değiştirebilirsin.',
'Do you want to create save data\nusing the following settings?\n  Difficulty [%ls]\n  Autosave [%ls]':'Aşağıdaki ayarlarla kayıt verisi\noluşturulsun mu?\n  Zorluk [%ls]\n  Otomatik Kayıt [%ls]',
'To make changes, return to the previous\nscreen and select again. You can also\nchange the settings from the Config\nscreen after starting.':'Değişiklik yapmak için önceki ekrana dönüp\nyeniden seç. Oyuna başladıktan sonra da\nAyarlar ekranından değiştirebilirsin.',
'<R>Save data already exists.</>\nDo you want to overwrite it?':'<R>Kayıt verisi zaten var.</>\nÜzerine yazılsın mı?',
'When you update data from the Save Menu in the\ngame, backup data is saved to the server.\nYou can restore your save data from this server\nbackup as long as all three save data slots are\nempty.':'Oyundaki Kayıt Menüsünden veriyi güncellediğinde\nyedek veri sunucuya kaydedilir. Üç kayıt yuvası da\nboş olduğu sürece kayıt verini bu sunucu\nyedeğinden geri yükleyebilirsin.',
'Download backup data?':'Yedek veri indirilsin mi?',
'There is no backup data on the server.':'Sunucuda yedek veri yok.',
'Backup data downloaded.\nSelect the slot to restore it to.':'Yedek veri indirildi.\nGeri yüklenecek yuvayı seç.',
'Cannot restore, as save data already exists.':'Kayıt verisi zaten olduğundan geri yüklenemez.',
'Restoring data.\nDo not turn off the power or\nremove the card.':'Veri geri yükleniyor.\nSistemi kapatma veya\nkartı çıkarma.',
'Data restored.\nReturning to the title screen.':'Veri geri yüklendi.\nBaşlık ekranına dönülüyor.',
'Return to the title screen without\nrestoring data?':'Veriyi geri yüklemeden\nbaşlık ekranına dönülsün mü?',
'Failed to restore data.\nReturning to the title screen.':'Veri geri yüklenemedi.\nBaşlık ekranına dönülüyor.',
'This game uses the gyro sensor.\nPlace the Nintendo 3DS system on a level surface,\nand leave it there for a while.\n\nBe careful to avoid hitting things or people around\nyou when playing.':'Bu oyun jiroskop sensörünü kullanır.\nNintendo 3DS sistemini düz bir yüzeye koyup\nbir süre dokunmadan bırak.\n\nOynarken çevrendeki eşya ve insanlara\nçarpmamaya dikkat et.',
'The gyro sensor is ready.\nPick up the Nintendo 3DS system with the 3D Screen\nfacing forward.':'Jiroskop sensörü hazır.\nNintendo 3DS sistemini 3D Ekran\nöne bakacak şekilde eline al.',
'Creating system and game data.\nDo not turn off the system or\nremove the card.':'Sistem ve oyun verisi oluşturuluyor.\nSistemi kapatma veya kartı çıkarma.',
'Failed to create data.':'Veri oluşturulamadı.',
'Created data.':'Veri oluşturuldu.',
'Failed to create data.\nReturning to the title screen.':'Veri oluşturulamadı.\nBaşlık ekranına dönülüyor.',
'The save data is corrupted.\nReturn to the title screen\nand delete the data.':'Kayıt verisi bozuk.\nBaşlık ekranına dönüp\nveriyi sil.',
'Changed character name.':'Karakter adı değiştirildi.',
'Level data.\nIncludes total experience acquired.':'Seviye verisi.\nToplam kazanılan deneyimi içerir.',
'Data for the jobs acquired.':'Edinilen mesleklerin verisi.',
'Job level data.\nIncludes data for support abilities\nand total job points acquired.':'Meslek seviyesi verisi. Destek yeteneklerini\nve toplam kazanılan JP’yi içerir.',
'Data for funds acquired.':'Kazanılan para verisi.',
'Item data.\nIncludes the magic scrolls acquired.\nDoes not include key items.':'Eşya verisi. Edinilen büyü parşömenlerini\niçerir; önemli eşyaları içermez.',
'Data for the genome abilities\nacquired.':'Edinilen genom yeteneklerinin\nverisi.',
'Population data for Norende Village.':'Norende Köyü nüfus verisi.',
'The status of the reconstruction of\nNorende Village.':'Norende Köyü yeniden inşa\ndurumu.',
'All data for D’s Journal that has been\nrevealed.\n*Scenes revealed in the Event\nViewer are transferred either way.':"D'nin Defteri'nde açığa çıkarılan tüm veriler.\n*Olay İzleyicide açılan sahneler her iki durumda\nda aktarılır.",
'Special move data.\nIncludes special move parts, names, and\nset status.':'Özel hamle verisi. Özel hamle parçalarını,\nadlarını ve ayarlı durumlarını içerir.',
'The total amount of time played.':'Toplam oynama süresi.',
'Data for friends added.':'Eklenen arkadaşların verisi.',
'Data for guests.':'Misafir verisi.',
'Continue to the next screen using\nthe selected details.':'Seçilen ayrıntılarla\nsonraki ekrana geç.',
'Continue to the next screen without transferring data.':'Veri aktarmadan sonraki ekrana geç.',

# AdventurerMessageData
'Test':'Test',
'There’s someone I’d like you\nto meet. What do you say?':'Tanışmanı istediğim biri var.\nNe dersin?',
'You became friends with\n%ls.':'%ls ile arkadaş oldun.',
'You made %d new friends.':'%d yeni arkadaş edindin.',
'Hard at work, I see.':'Sıkı çalışıyorsun, görüyorum.',
'Your AI Friend data has been\nupdated.':'Yapay Zekâ Arkadaş verin\ngüncellendi.',
'Now showing AI Friend data.':'Yapay Zekâ Arkadaş verisi gösteriliyor.',
'The save data is corrupt and must\nbe remade. Continue?':'Kayıt verisi bozuk ve yeniden\noluşturulmalı. Devam edilsin mi?',
'Deleting data. Please do not\nturn off the system or remove\nthe card.':'Veri siliniyor. Lütfen sistemi\nkapatma veya kartı çıkarma.',
'Could not delete data. Now\nreturning to the game.':'Veri silinemedi.\nOyuna dönülüyor.',
'It only gets worse\nfrom here on in…':'Bundan sonrası\ndaha da zorlaşacak…',
'Whatever’s in that\nlight…it’s strong.':'O ışığın içindeki her neyse…\nçok güçlü.',
'How are you feeling?':'Nasıl hissediyorsun?',
'It’s the start of a new\nadventure, eh?':'Yeni bir maceranın\nbaşlangıcı, ha?',
'Heh, you look as if you’re\nhaving a strange day.':'Heh, tuhaf bir gün\ngeçiriyor gibisin.',
'If you’re feeling unsure,\nask around. Some people\nhave good advice to offer.':'Emin değilsen etrafa sor.\nBazı insanların verecek\ngüzel öğütleri vardır.',
'You look dog tired. It’s\nimportant to know when\nto rest.':'Çok yorgun görünüyorsun.\nNe zaman dinleneceğini\nbilmek önemlidir.',
'Even the harshest journeys\nhave a way of becoming\nfond memories.':'En zorlu yolculuklar bile\nzamanla güzel anılara\ndönüşebilir.',
'Come what may, your journey\nwon’t stop till you do.':'Ne olursa olsun, sen durmadıkça\nyolculuğun da durmayacak.',
'Excited by your first real\njourney? Good. There’s no\npoint if it stops being fun.':'İlk gerçek yolculuğun heyecanlı mı?\nGüzel. Eğlenceli olmaktan çıkarsa\nzaten anlamı kalmaz.',
'How goes?':'Nasıl gidiyor?',
'Head straight for your goal,\nor take a few detours on the\nway—it’s your journey.':'Doğruca hedefine git ya da yolda\nbiraz dolan. Bu senin yolculuğun.',
'Up and down, sink or swim…\nThis place is a lot like life.':'İniş çıkış, batmak ya da yüzmek…\nBurası hayata çok benziyor.',
'Company on the road is a\nprecious thing. Treat your\nfriends well.':'Yolda bir yoldaşın olması değerlidir.\nArkadaşlarına iyi davran.',
'It’s just as you catch your\nstride you’re most likely to\ntrip. Don’t get careless.':'Tam ritmini bulduğunda tökezlemek\nen kolaydır. Dikkati elden bırakma.',
'It’s nearly the big moment,\neh?':'Büyük an yaklaşıyor,\nöyle mi?',
'I’m impressed you made it\nall the way out here.':'Buralara kadar gelmene\ngerçekten şaşırdım.',
'Sometimes the shortest way\nthere is the long way ’round.':'Bazen en kısa yol,\ndolanarak gidilen yoldur.',
'You’ve come so far. Just a\nlittle further, now.':'Bunca yol geldin.\nŞimdi biraz daha dayan.',
'Rough road, eh? You’re\nnearly to Florem, though.':'Zorlu yol, değil mi?\nYine de Florem’e az kaldı.',
'The same road looks pretty\ndifferent coming and going,\nhuh?':'Aynı yol gidişte ve dönüşte\nepey farklı görünüyor, değil mi?',
'Just try to be careful.\nThat’s all I ask.':'Sadece dikkatli ol.\nTek istediğim bu.',
'You made it at last…':'Sonunda başardın…',

# Unarranged / Note / Event / Quest / Shop / legacy strings
'Save data is corrupted.\nSelect Data Reset from the\ntitle screen to delete the\ndata.':'Kayıt verisi bozuk. Veriyi silmek için\nbaşlık ekranından Veri Sıfırlama’yı seç.',
'You cannot enter the airship right now.':'Şu anda hava gemisine giremezsin.',
'You cannot use autopilot right now.':'Şu anda otomatik pilotu kullanamazsın.',
"[FRIENDNM]'s World":'[FRIENDNM] Dünyası',
'You cannot exit the airship right now.':'Şu anda hava gemisinden çıkamazsın.',
'Delete save data and related\nsystem data and restore defaults?':'Kayıt ve ilgili sistem verileri silinip\nvarsayılanlara dönülsün mü?',
'Save data is corrupted.\nSelect Data Reset from the\ntitle screen to delete the data.':'Kayıt verisi bozuk. Veriyi silmek için\nbaşlık ekranından Veri Sıfırlama’yı seç.',
'Save cleared game data?\nNote: If you save, the game will\nresume from before the attempt to\ndestroy the crystal.':'Tamamlanmış oyun verisi kaydedilsin mi?\nNot: Kaydedersen oyun, kristali yok etme\ngirişiminden önce devam eder.',
'Save cleared game data?\nNote: If you save, the game will\nresume from before awakening the\nlast four crystals.':'Tamamlanmış oyun verisi kaydedilsin mi?\nNot: Kaydedersen oyun, son dört kristali\nuyandırmadan önce devam eder.',
'Are you sure you want to return to\nthe title screen without saving\ncleared game data?':'Tamamlanmış oyun verisini kaydetmeden\nbaşlık ekranına dönmek istediğinden emin misin?',
'Saved.\nContinue your journey in\nsearch of new horizons.':'Kaydedildi.\nYeni ufuklar aramak için\nyolculuğuna devam et.',
'Saved.\nContinue to enjoy the game.':'Kaydedildi.\nOyunun tadını çıkarmaya devam et.',
'Game Completion Bonus\n\n[PCF1] can now equip\nthe vestal garb.':'Oyunu Bitirme Bonusu\n\n[PCF1] artık Vestal\ngiysisini kuşanabilir.',
'Game Completion Bonus\n\nA special movie is\nnow available to watch.':'Oyunu Bitirme Bonusu\n\nArtık özel bir video\nizlenebilir.',
'"New Game+" has been added.\nYou can carry over your data to\nenjoy the game from the beginning.':'“Yeni Oyun+” eklendi.\nVerilerini aktararak oyuna\nbaştan başlayabilirsin.',
'Save data is corrupted, and will need\nto be recreated. Okay to proceed?':'Kayıt verisi bozuk ve yeniden oluşturulmalı.\nDevam edilsin mi?',
'Failed to delete data.\nTry saving again?':'Veri silinemedi.\nYeniden kaydetmeyi dene?',
'Save data recreated.':'Kayıt verisi yeniden oluşturuldu.',
"We'd like to give you a gift\nfor playing the demo version!":'Demo sürümünü oynadığın için\nsana bir hediye vermek istiyoruz!',
"That's all for now.\nEnjoy the rest of the game!":'Şimdilik bu kadar.\nOyunun geri kalanının tadını çıkar!',
'Save data already exists.\nOkay to overwrite it?':'Kayıt verisi zaten var.\nÜzerine yazılsın mı?',
'Previous data will be lost.\nAre you certain?':'Önceki veriler kaybolacak.\nEmin misin?',
'Save data is corrupted.\nReturning to the title screen.':'Kayıt verisi bozuk.\nBaşlık ekranına dönülüyor.',
'An error has occurred.\nPlease wait a while and try again.\n':'Bir hata oluştu.\nBir süre bekleyip yeniden dene.\n',
'Mysterious text that seems to detail future events.':'Gelecekteki olayları anlatıyor gibi görünen gizemli metin.',
'Information you have obtained during your travels.':'Yolculukların sırasında edindiğin bilgiler.',
'Check your progress and view explanations.':'İlerlemeni kontrol et ve açıklamaları görüntüle.',
'View tutorials you have already seen once.':'Daha önce gördüğün eğitimleri görüntüle.',
'View job characteristics and equipment aptitude.':'Meslek özelliklerini ve teçhizat yetkinliğini görüntüle.',
'The journal of the dark knight Alternis Dim.':'Kara şövalye Alternis Dim’in günlüğü.',
'View events that have occurred in the past.':'Geçmişte gerçekleşen olayları görüntüle.',
'Turn pages using the Touch Screen (or the L/R Buttons).':'Dokunmatik Ekranla (veya L/R Düğmeleriyle) sayfaları çevir.',
'%d Times':'%d Kez',
"The Fairy's Call":'Perinin Çağrısı',
'Four Tales':'Dört Hikâye',
'Reunion Promise':'Yeniden Buluşma Sözü',
'%2d/%2d completed':'%2d/%2d tamamlandı',
'CLEAR!\n\n':'TAMAMLANDI!\n\n',
'Select a character whose equipment to change.':'Teçhizatı değiştirilecek karakteri seç.',
'Restore HP/MP and cure status ailments such as K.O.':'HP/MP’yi yenile ve K.O. gibi durum etkilerini iyileştir.',
'Return to the map without staying at the inn.':'Handa konaklamadan haritaya dön.',
'「%ls」×%dを入手した':'「%ls」×%d elde edildi.',
'「%ls」×%dを入手':'「%ls」×%d elde edildi.',
'インターネットブラウザーを起動して\n%ls\n表示しますか？ \n※ＨＯＭＥボタンから再開で戻れます。':'İnternet tarayıcısı açılıp\n%ls\ngörüntülensin mi?\n* HOME düğmesinden oyuna dönebilirsin.',
'既に他ユーザによって\n利用されているメンバーズアカウント\nと紐付いているため、\nROMを初期化してください。':'Bu Members hesabı başka bir kullanıcıyla\neşleştirilmiş. Lütfen oyun verisini sıfırla.',
'メンバーズIDとパスワードの再送信が必要です。\n「送信」ボタンをタッチしてください。':'Members kimliği ve parolasının yeniden gönderilmesi gerekiyor.\n“Gönder” düğmesine dokun.',
'こちらからスクエニメンバーズサービスの\n利用登録をすることができます。\nご褒美アイテム\nお助けアイテム\nなど、特典がいっぱい！\n期間限定のイベントも開催しているよ\n\n詳しくはこちら\nスクエア・エニックスメンバーズサイト\nhttp://member.square-enix.com':'Buradan Square Enix Members hizmetine\nkayıt olabilirsin. Ödül ve yardım eşyaları\ngibi birçok avantajın yanı sıra sınırlı süreli\netkinlikler de var.\n\nAyrıntılar:\nSquare Enix Members sitesi\nhttp://member.square-enix.com',
}
