# -*- coding: utf-8 -*-
"""Additional Common_en UI/system translations found untranslated in the user's workbooks.
Only exact source-string matches are replaced, and already-translated cells are never overwritten.
"""
MESSAGE_SUPPLEMENTAL = {
    'No':'Hayır','OK':'Tamam','On':'Açık','Off':'Kapalı','Close':'Kapat','Continue':'Devam','Quit':'Çık',
    'Buy':'Al','Stay':'Konakla','None':'Yok','Easy':'Kolay','Hard':'Zor','Fast':'Hızlı',
    'Intro':'Giriş','Finale':'Final','The End':'Son','View All':'Tümünü Gör','Subtitles':'Altyazılar',
    'Playback':'Oynat','Delete':'Sil','Remember':'Hatırla','Fixed':'Sabit',
    'Newest to Oldest':'Yeniden Eskiye','Most to Least Power':'En Güçlüden Zayıfa',
    'Most to Least Affinity':'En Yüksek Yakınlıktan Düşüğe',
    'Protect/Unprotect':'Koru/Korumayı Kaldır','Stop/Resume Updating':'Güncellemeyi Durdur/Sürdür',
    'Host Unit':'Ana Birim','Client Unit':'İstemci Birim','Guest List':'Misafir Listesi',
    'Character Name':'Karakter Adı','Level':'Seviye','Job Level':'Meslek Seviyesi',
    'Special Moves':'Özel Hamleler','Play time':'Oyun Süresi','Genome Abilities':'Genom Yetenekleri',
    'Consumables':'Tüketilebilirler','Weapons':'Silahlar','Head Armor':'Baş Zırhı','Torso Armor':'Gövde Zırhı',
    'Accessories':'Aksesuarlar','Humanoids':'İnsansılar','Beasts':'Canavarlar','Aerial':'Uçanlar',
    'Aquatic':'Sucullar','Bugs':'Böcekler','Plants':'Bitkiler','Undead':'Ölümsüzler',
    'Demonkind':'İblisler','Dragonkind':'Ejderler','Inorganic':'Cansızlar','Bosses':'Bosslar','Outfits':'Kıyafetler',
    'Paralyze':'Felç','Dread':'Dehşet','Confuse':'Şaşkınlık','Mirror':'Yansıt','Resist':'Direnç',
    'Nullify':'Geçersiz Kıl','Absorb':'Em',
    'Ch. 1':'Bölüm 1','Ch. 2':'Bölüm 2','Ch. 3':'Bölüm 3','Ch. 4':'Bölüm 4',
    'Ch. 5':'Bölüm 5','Ch. 6':'Bölüm 6','Ch. 7':'Bölüm 7','Ch. 8':'Bölüm 8',

    # Event Viewer
    'View main scenario events.':'Ana senaryo olaylarını görüntüle.',
    'View sub-scenario events.':'Yan senaryo olaylarını görüntüle.',
    'View party chat events.':'Parti sohbeti olaylarını görüntüle.',
    'Select a chapter.':'Bir bölüm seç.', 'Select a movie.':'Bir video seç.',
    'Select an event to view.':'Görüntülenecek olayı seç.',
    'View all events that have occurred so far.':'Şimdiye kadarki tüm olayları görüntüle.',
    'Skip event?':'Olay atlansın mı?', 'Play movie events.':'Video olaylarını oynat.',

    # Menu / configuration help
    'Change jobs?':'Meslek değiştirilsin mi?', 'Go to Abilities.':'Yeteneklere git.', 'Go to Equip.':'Kuşanma ekranına git.',
    'Set a job command.':'Bir meslek komutu ayarla.', 'Set support abilities.':'Destek yeteneklerini ayarla.',
    'Commands currently available.':'Şu anda kullanılabilen komutlar.', 'Job characteristics.':'Meslek özellikleri.',
    'Remove the set job command.':'Ayarlı meslek komutunu kaldır.', 'Job command':'Meslek komutu',
    'Equip a support ability.':'Bir destek yeteneği kuşan.', 'Select an ability for the %ls.':'%ls için bir yetenek seç.',
    'Select a job.':'Bir meslek seç.', 'Remove the selected ability.':'Seçili yeteneği kaldır.',
    'Equipment changed.':'Teçhizat değiştirildi.',
    'Nothing equipped.':'Hiçbir şey kuşanılmamış.',
    'Set the cursor behavior in the game.':'Oyundaki imleç davranışını ayarla.',
    'Set the volume of sound effects in the game.':'Oyundaki efekt seslerinin seviyesini ayarla.',
    'Set the volume of music in the game.':'Oyundaki müzik sesini ayarla.',
    'Set the volume of voices in the game.':'Oyundaki seslendirme seviyesini ayarla.',
    'Set the message speed in the game.':'Oyundaki mesaj hızını ayarla.',
    'Set whether to update data after using Send in battle.':'Savaşta Gönder kullandıktan sonra verinin güncellenip güncellenmeyeceğini ayarla.',
    'Reset all settings.':'Tüm ayarları sıfırla.',
    'Keep the cursor position after closing windows.':'Pencereler kapandıktan sonra imleç konumunu koru.',
    'Reset the cursor position after closing windows.':'Pencereler kapandıktan sonra imleç konumunu sıfırla.',
    'Press up/down to set the sound effect volume.':'Efekt sesi için yukarı/aşağı bas.',
    'Press up/down to set the music volume.':'Müzik sesi için yukarı/aşağı bas.',
    'Press up/down to set the voice volume.':'Seslendirme için yukarı/aşağı bas.',
    'Set the slowest message speed.':'En yavaş mesaj hızını seç.',
    'Set normal message speed.':'Normal mesaj hızını seç.',
    'Set the fastest message speed.':'En hızlı mesaj hızını seç.',
    'Update your data after using Send in battle.':'Savaşta Gönder kullandıktan sonra verini güncelle.',
    'Do not update your data after using Send in battle.':'Savaşta Gönder kullandıktan sonra verini güncelleme.',
    'Reset the %ls settings.':'%ls ayarlarını sıfırla.',

    # Common save/network UI
    'Are you sure you’d like\nto save?':'Kaydetmek istediğine\nemin misin?',
    'Now saving. Please do not turn off\nthe system or remove the card.':'Kaydediliyor. Sistemi kapatma\nve kartı çıkarma.',
    'Save complete.\nContinue playing?':'Kayıt tamamlandı.\nOynamaya devam edilsin mi?',
    'Save failed. Try again?':'Kayıt başarısız. Tekrar denensin mi?',
    'Save your current adventure progress.':'Mevcut macera ilerlemeni kaydet.',
    'Update data via an Internet connection.':'Veriyi internet bağlantısıyla güncelle.',
    'Register Friends.':'Arkadaş kaydet.', 'Return to the title screen.':'Başlık ekranına dön.',
    'Are you sure you want to return to\nthe title screen? Any unsaved data\nwill be lost.':'Başlık ekranına dönmek istediğine emin misin?\nKaydedilmemiş veriler kaybolacak.',
    'Connecting to the Internet\nmay take time. Continue\nanyway?':'İnternete bağlanmak zaman alabilir.\nYine de devam edilsin mi?',
    'Updating profile data…':'Profil verisi güncelleniyor…','Updating Friend data…':'Arkadaş verisi güncelleniyor…',
    'Uploading save data…':'Kayıt verisi yükleniyor…','Receiving quest items…':'Görev eşyaları alınıyor…',
    'Net-inviting Friends…':'Arkadaşlara internet daveti gönderiliyor…','Receiving nemesis data…':'Nemesis verisi alınıyor…',
    'Do not turn off the system while updating.':'Güncelleme sırasında sistemi kapatma.',
    'Data update complete.':'Veri güncellemesi tamamlandı.',
    'You received “%ls” ×%d.':'“%ls” ×%d alındı.',
    '%ls’s\ndata has been updated.':'%ls adlı oyuncunun\nverisi güncellendi.',

    # Shop UI help
    'Buy equipment sold at the shop.':'Dükkânda satılan teçhizatı satın al.',
    'Sell items in your inventory.':'Envanterindeki eşyaları sat.',
    'Change your equipment in another room.':'Teçhizatını diğer odada değiştir.',
    'View weapons.':'Silahları görüntüle.','View shields.':'Kalkanları görüntüle.',
    'View head armor.':'Baş zırhlarını görüntüle.','View torso armor.':'Gövde zırhlarını görüntüle.',
    'View accessories.':'Aksesuarları görüntüle.','Buy consumable items.':'Tüketilebilir eşya satın al.',
    'Buy magic scrolls.':'Büyü parşömeni satın al.','Press confirm to buy a magic scroll.':'Büyü parşömeni almak için onayla.',
    'Sell weapons in your inventory.':'Envanterindeki silahları sat.',
    'Sell armor/accessories in your inventory.':'Envanterindeki zırh ve aksesuarları sat.',
    'Sell consumable items in your inventory.':'Envanterindeki tüketilebilir eşyaları sat.',
    'Raise/lower buying quantity. Press confirm to buy.':'Alım miktarını artır/azalt. Satın almak için onayla.',
    'Raise/lower selling quantity. Press confirm to sell.':'Satış miktarını artır/azalt. Satmak için onayla.',
    'View outfits that change appearance.':'Görünüşü değiştiren kıyafetleri görüntüle.',
    'Sell outfits in your inventory.':'Envanterindeki kıyafetleri sat.',

    # Title / friend list common labels
    'Select the data to copy.':'Kopyalanacak veriyi seç.','Select the slot to copy to.':'Kopyalanacak yuvayı seç.',
    'Select the data to delete.':'Silinecek veriyi seç.','Select the data to transfer over.':'Aktarılacak veriyi seç.',
    'Select a difficulty.':'Bir zorluk seç.','Do you want to autosave?':'Otomatik kayıt açılsın mı?',
    'Select a slot to save to.':'Kaydedilecek yuvayı seç.',
    'Norende Village Population':'Norende Köyü Nüfusu','Norende Village Status':'Norende Köyü Durumu',
    'D’s Journal':"D'nin Defteri", 'Friends':'Arkadaşlar','Guests':'Misafirler',
    'Sort':'Sırala','Data List':'Veri Listesi','Cannot access the network.':'Ağa erişilemiyor.',
    'Add friends.':'Arkadaş ekle.','Update data.':'Veriyi güncelle.','Show Friends.':'Arkadaşları göster.',
    'Show Guest List.':'Misafir listesini göster.','Showing friend profiles.':'Arkadaş profilleri gösteriliyor.',
    'Showing guest profiles.':'Misafir profilleri gösteriliyor.',
    'Select a friend to delete.':'Silinecek arkadaşı seç.','Select a friend to update.':'Güncellenecek arkadaşı seç.',
    'Update StreetPass data.':'StreetPass verisini güncelle.','Change the sorting order of friends.':'Arkadaşların sıralamasını değiştir.',
    'Delete a friend from the list.':'Arkadaşı listeden sil.','Change the sorting order of guests.':'Misafirlerin sıralamasını değiştir.',
    'Protect or unprotect guest data.':'Misafir verisini koru veya korumayı kaldır.','Delete a guest from the list.':'Misafiri listeden sil.',

    # Basic miscellaneous prompts
    'Enter a name.':'Bir ad gir.','Use this name?':'Bu ad kullanılsın mı?','Enter Airship':'Hava Gemisine Bin',
    'Pilot Yourself':'Kendin Kullan','Not possible here.':'Burada yapılamaz.','Are you sure?':'Emin misin?',
    'Data created.':'Veri oluşturuldu.','Save complete.':'Kayıt tamamlandı.','Return to the title screen?':'Başlık ekranına dönülsün mü?',
    'Failed to read SD Card.':'SD Kart okunamadı.','Will you accept it?':'Kabul ediyor musun?',
}
