# -*- coding: utf-8 -*-
STRUCTURED_TR={
'Lower one target’s Speed for 4 turns':'Bir hedefin Hızını 4 tur düşürür',
'Good chance of fleeing from battle':'Savaştan kaçma şansını büyük ölçüde artırır',
'Select target of enemy action for that turn':'O tur düşman eyleminin hedefini seçer',
'Powerful counter when taking major damage':'Büyük hasar alınca güçlü bir karşı saldırı yapar',
'Attack and lower target’s Speed':'Saldırır ve hedefin Hızını düşürür',
'Charm a demonkind target':'İblis türü bir hedefi büyüler',
'Charm one target':'Bir hedefi büyüler',
'Charm all enemies':'Tüm düşmanları büyüler',
'Dark-based magic that kills allies/enemies in Sleep state':'Uyku durumundaki dost veya düşmanı öldüren karanlık büyü',
'Give one ally immunity to all elements for 5 turns':'Bir müttefiki 5 tur tüm elementlere karşı bağışık kılar',
'Reduce elemental damage to all allies for 5 turns':'Tüm müttefiklerin element hasarını 5 tur azaltır',
'Prevent status ailments for all allies for 5 turns':'Tüm müttefiklerde durum bozukluklarını 5 tur engeller',
'Raise all allies’ speed for 4 turns':'Tüm müttefiklerin Hızını 4 tur artırır',
'Time Mage':'Zaman Büyücüsü',
'How’s this?':'Nasılmış?',
'Get ready!':'Hazır ol!',
'Everyone okay?':'Herkes iyi mi?',
'Here goes…':'İşte geliyor…',
'Hang in there!':'Dayanın!',
'Good to go!':'Hazırım!',
'Soothing, huh?':'Rahatlatıcı, değil mi?',
'Time for Plan B.':'B Planı zamanı.',
'Shopping in Hartschild ':'Hartschild’da Alışveriş',
}

# Legacy / system strings that can still surface on edge paths.
MESSAGE_V33_TR={
'はい':'Evet','いいえ':'Hayır',
'セーブしています\n電源を切ったり、カードを\n抜き差ししないでください':'Kaydediliyor.\nGücü kapatmayın veya oyun kartını\nçıkarıp takmayın.',
'セーブデータを\n読み込んでいます':'Kayıt verisi\nyükleniyor.',
'システムデータをセーブしています。\n電源を切ったり、カードを\n抜き差ししないでください':'Sistem verisi kaydediliyor.\nGücü kapatmayın veya oyun kartını\nçıkarıp takmayın.',
'セーブしました。':'Kaydedildi.',
'セーブに失敗しました。':'Kaydetme başarısız.',
'閉じる':'Kapat',
'アチーブメント':'Başarımlar',
'ブレイブリークエスト':'Bravely Görevleri',
'パスワード':'Parola',
'ワンタイムパスワード':'Tek Kullanımlık Parola',
'あなたのブレイブリーコード':'Bravely Kodun',
'インターネット通信中・・・':'İnternete bağlanılıyor…',
'アップロードが完了しました':'Yükleme tamamlandı.',
'通信が中断されました':'Bağlantı kesildi.',
'開催中のブレイブリークエストは\nありません':'Şu anda etkin Bravely Görevi yok.',
'表示するクエストはありません。\nデータ更新をすると、データが取得できます。':'Gösterilecek görev yok.\nVerileri güncelleyerek görevleri alabilirsiniz.',
}
