# -*- coding: utf-8 -*-
SHOP_TR = {
'That look right?':'Böyle uygun mu?',
'How many do you need?':'Kaç tane lazım?',
'Does that sound good?':'Uygun mudur?',
'Do we have a deal?':'Anlaştık mı?',
'We’re agreed, then?':'Öyleyse anlaştık mı?',
'You’ve made your decision?':'Kararını verdin mi?',
'You’ve decided, then?':'Demek kararını verdin?',
'You’re certain, then?':'Eminsin, değil mi?',
'Care to put it on now?':'Şimdi kuşanmak ister misin?',
'Got all you needed?':'İhtiyacın olan her şeyi aldın mı?',
'Nothing else I can do\nfor you?':'Başka yardımcı olabileceğim\nbir şey yok mu?',
'Hope it’s of use!':'Umarım işine yarar!',
'And who’ll wear it?':'Bunu kim kuşanacak?',
'Best to equip that\nstraightaway.':'En iyisi onu hemen\nkuşanmak.',
'Leaving already?':'Şimdiden gidiyor musun?',
'Come again soon!':'Yine beklerim!',
'How many did you have to sell?':'Kaç tane satacaktın?',
'Take care of that, now!':'İyi kullan!',
'You’ve got a deal!':'Anlaştık!',
'Which one of you is\nchanging equipment?':'Hanginiz ekipmanını\ndeğiştirecek?',
'Planning to wear that\nout, dear?':'Onu şimdi kuşanacak\nmısın, canım?',
'Leaving so soon?':'Bu kadar çabuk mu gidiyorsun?',
'Come any time, dear.\nI’ll be waiting.':'İstediğin zaman gel, canım.\nSeni beklerim.',
'Thank you, dear.':'Teşekkürler, canım.',
'Sounds like a deal.':'Anlaşmaya benziyor.',
'Which of you dears is\nwearing that?':'Hanginiz bunu\nkuşanacak, canım?',
'Will you be changing\ninto that now?':'Şimdi onu\nkuşanacak mısın?',
'That everything, then?':'Hepsi bu mu?',
'Best of luck, now.':'Bol şans.',
'And who will be\nchanging?':'Peki kim\ndeğiştirecek?',
'You can change into\nthat here, if you like.':'İstersen onu burada\nkuşanabilirsin.',
'Leaving? Mmm, but\nyou only just got here.':'Gidiyor musun? Hımm,\ndaha yeni gelmiştin.',
'I’ll be waiting with the\nbest arms available.':'En iyi silahlarla\nseni bekliyor olacağım.',
'Be gentle with that, hmm?':'Ona iyi bak, olur mu?',
'Mmm, deal.':'Hımm, anlaştık.',
'Who is changing\nequipment?':'Kim ekipmanını\ndeğiştirecek?',
'Will you wear that\nnow?':'Şimdi onu\nkuşanacak mısın?',
'Heading out?':'Gidiyor musun?',
'Don’t be a stranger.':'Yine uğra.',
'It’s all yours!':'Tamamen senin!',
'I’ll take good care of it.':'Ona iyi bakarım.',
'Who will be changing\ntheir equipment?':'Kim ekipmanını\ndeğiştirecek?',
'Changing your\nequipment here?':'Ekipmanını burada mı\ndeğiştireceksin?',
'Done shopping?':'Alışveriş bitti mi?',
'Take care!':'Kendine iyi bak!',
'A fair bargain.':'Adil bir alışveriş.',
'Who is equipping this?':'Bunu kim kuşanacak?',
'You can change your\nequipment here.':'Ekipmanını burada\ndeğiştirebilirsin.',
'As long as you’re\nsatisfied your defense\nis perfect.':'Savunmandan memnunsan\nher şey yolunda.',
'May victory be yours.':'Zafer senin olsun.',
'Let that keep you safe.':'Bu seni korusun.',
'Hmm, deal.':'Hımm, anlaştık.',
'Which one of you is\nthat for?':'Bu hanginiz için?',
'Why not put that on\nstraightaway?':'Neden onu hemen\nkuşanmıyorsun?',
'Made your decision,\nhave you?':'Kararını verdin\ndemek?',
'How many do you want?':'Kaç tane istiyorsun?',
'Use it well.':'İyi kullan.',
'I’ll find it a good home.':'Ona iyi bir yer bulurum.',
'Which of you is\nequipping that?':'Hanginiz onu\nkuşanacak?',
'Some abilities allow\nyou to equip heavier\ngear.':'Bazı yetenekler daha ağır\nekipman kuşanmanı\nsağlar.',
'Hmm, all prepared\nfor the road?':'Hımm, yolculuğa\nhazır mısın?',
'Next time, then. I’m\nlooking forward to it.':'Bir dahaki sefere.\nSeni bekliyorum.',
'Use it to the fullest.':'Hakkını vererek kullan.',
'Invest this in good armor.':'Bunu iyi bir zırha yatır.',
'Which of you is putting\nthat on?':'Hanginiz onu\nkuşanıyor?',
}
